import baits from './baits-data.json' with {type:'json'};
import {TECHNIQUES,RECIPES} from './techniques.ts';
import type {Component,Slot} from './rig.ts';
import type {MethodId} from './specimens.ts';
export const EXTRA_SLOT_NAMES={backing:'Backing',fly_line:'Soie',tippet:'Pointe',feeder:'Cage / method',bombette:'Bombette',fly:'Mouche / imitations',groundbait:'Amorce',swivel:'Émerillon',snap:'Agrafe',stop:'Stop',bead:'Perle',lead_clip:'Clip-plomb',tube:'Tube',boom:'Potence',hair:'Cheveu',pva:'PVA soluble',indicator:'Indicateur',jig_head:'Tête plombée',nail_weight:'Insert de lest',wire_arm:'Tige déportée',harness:'Monture',clonk:'Clonk',landing:'Réception'};
const all:MethodId[]=['pole','float','bottom','lure'];
const effects:Partial<Record<Slot,Partial<Component>>>={
 main_line:{strength:1},leader:{strength:.9},elastic:{control:1.18},reel:{control:1},backing:{strength:1.2},fly_line:{strength:1.1,mass:8,sinkSpeed:.12},tippet:{strength:.85},float:{capacity:2,integrated:0},weight:{mass:10},feeder:{mass:20,diffusion:35},bombette:{mass:12,buoyancy:'float'},fly:{mass:.3,diet:'invertebrates',buoyancy:'sink',size:6},groundbait:{diet:'plants',diffusion:35},jig_head:{mass:5},nail_weight:{mass:1.2},harness:{mass:4},pva:{diffusion:8},landing:{capacity:250},hook:{size:6},bait:{mass:.15,diet:'invertebrates',retention:1,size:8},lure:{mass:5,diet:'fish',size:50},hair:{length:.025},
} as Partial<Record<Slot,Partial<Component>>>;
const slotName=(slot:Slot)=>EXTRA_SLOT_NAMES[slot as keyof typeof EXTRA_SLOT_NAMES]??({main_line:'Fil',leader:'Bas de ligne',elastic:'Élastique',reel:'Moulinet',float:'Flotteur',weight:'Lest',attachment:'Fixation',hook:'Hameçon',bait:'Esche',lure:'Leurre'} as Record<string,string>)[slot];
const slots=[...new Set([...RECIPES.flatMap(r=>r.slots),'reel','elastic','main_line','landing'])] as Slot[];
export const EXTRA_COMPONENTS:Component[]=[
 ...slots.flatMap(slot=>[true,false].map(free=>({id:`${free?'kit2':'v2'}:${slot}`,name:`${slotName(slot)} ${free?'de secours':'réglable'}`,slot,methods:[...all],family:slot,free,price:free?0:['reel','fly_line','landing'].includes(slot)?35:slot==='main_line'?20:8,pack:slot==='main_line'||slot==='backing'||slot==='fly_line'?100:slot==='leader'||slot==='tippet'?10:slot==='bait'||slot==='groundbait'?15:5,unit:['main_line','backing','fly_line','leader','tippet'].includes(slot)?'m' as const:['bait','groundbait'].includes(slot)?'portion' as const:'pièce' as const,...effects[slot],...(free?{}:slot==='weight'?{mass:15}:slot==='feeder'?{mass:30,diffusion:45}:slot==='tippet'||slot==='leader'?{strength:.78}:slot==='reel'||slot==='elastic'?{control:1.12}:slot==='float'?{capacity:3,integrated:1.3}:slot==='fly_line'?{sinkSpeed:.3}:{}),description:`${slotName(slot)} paramétré pour le prototype ; ${free?'secours gratuit non revendable':'prix par lot, stock et pertes actifs'}.`}))),
 {id:'kit2:pellet-float',name:'Waggler préplombé de secours',slot:'float',methods:all,family:'waggler',free:true,price:0,pack:1,unit:'pièce',capacity:2,integrated:1.85,description:'Plombée intégrée ; aucune masse externe requise.'},
 {id:'kit2:topwater',name:'Leurre de surface de secours',slot:'lure',methods:all,family:'topwater',free:true,price:0,pack:1,unit:'pièce',diet:'fish',mass:1,buoyancy:'float',description:'Surface, animation et pauses ; armement intégré.'},
 {id:'kit2:sinking-bombette',name:'Bombette plongeante de secours',slot:'bombette',methods:all,family:'bombette',free:true,price:0,pack:1,unit:'pièce',mass:12,buoyancy:'sink',description:'Corps porteur descendant, distinct de la flottabilité de l’esche.'},
 {id:'kit2:bread',name:'Pain flottant de secours',slot:'bait',methods:all,family:'pain',free:true,price:0,pack:1,unit:'portion',diet:'plants',buoyancy:'float',retention:.8,size:10,description:'Esche de surface, consommée par ligne ; inspection avant la prise.'},
 {id:'kit2:wafter',name:'Wafter de secours',slot:'bait',methods:all,family:'wafter',free:true,price:0,pack:1,unit:'portion',diet:'plants',buoyancy:'balanced',retention:1,size:10,description:'Esche équilibrée proche du fond, adaptée au method et au cheveu.'},
 {id:'kit2:popup',name:'Pop-up de secours',slot:'bait',methods:all,family:'pop_up',free:true,price:0,pack:1,unit:'portion',diet:'plants',buoyancy:'float',retention:1,size:12,description:'Surélève le cheveu près du fond ; nécessite un terminal qui la retient.'},
 {id:'kit2:deadfish',name:'Poisson-appât mort de secours',slot:'bait',methods:all,family:'poisson_mort',free:true,price:0,pack:1,unit:'portion',diet:'fish',buoyancy:'sink',mass:10,retention:1,size:70,description:'Monture consumant un poisson-appât par ligne engagée.'},
 {id:'kit2:dry-fly',name:'Mouche sèche de secours',slot:'fly',methods:all,family:'seche',free:true,price:0,pack:1,unit:'pièce',diet:'invertebrates',buoyancy:'float',mass:.08,size:6,description:'Imitation de surface ; dérive et gobage.'},
 {id:'kit2:streamer',name:'Streamer de secours',slot:'fly',methods:all,family:'streamer',free:true,price:0,pack:1,unit:'pièce',diet:'fish',buoyancy:'sink',mass:1,size:40,description:'Imitation animée, récupération et pauses nécessaires.'},
 ...baits.map(b=>{const slot:Slot=b.family==='amorcage'?'groundbait':b.family==='mouche'?'fly':b.family==='artificiel'?'bait':b.consumption==='portion'||b.consumption==='portion_amorcage'?'bait':'lure';const methods=[...new Set(TECHNIQUES.filter(t=>b.techniques.includes(t.id)).map(t=>t.base))];const diet:Component['diet']=b.diet.some(d=>d.includes('poisson')||d.includes('alevin'))?'fish':b.diet.some(d=>d.includes('veget')||d.includes('graine'))?'plants':'invertebrates';return {id:`bait:${b.id}`,name:b.name,slot,methods:methods.length?methods:all,techniques:b.techniques,family:b.family,free:false,price:slot==='lure'||slot==='fly'?18:8,pack:slot==='lure'||slot==='fly'?1:15,unit:slot==='lure'||slot==='fly'?'pièce' as const:'portion' as const,diet,size:b.tags.includes('petit')?4:b.tags.includes('gros')?50:12,mass:slot==='lure'?b.tags.includes('surface')?.5:5:slot==='fly'?.3:.15,buoyancy:b.tags.includes('flotte')||b.tags.includes('flottant')||b.tags.includes('surface')?'float' as const:b.tags.includes('equilibre')?'balanced' as const:'sink' as const,consumable:b.consumption==='portion'||b.consumption==='portion_amorcage',retention:b.tags.includes('fragile')||b.tags.includes('mou')?.7:1,diffusion:slot==='groundbait'?35:undefined,description:`${b.name} : ${b.tags.join(', ')}. Prix et physique de jeu configurés ; régime compatible requis.`};}),
];
