import {component,slotsFor,available,quantityFor,floatLoad,type Component,type RigConfig,type Tackle} from './rig.ts';
import {techniqueFor} from './techniques.ts';import {initialPresentation,stepPresentation} from './presentation.ts';
export function componentAdvice(i:Component){
 const roles:Partial<Record<Component['slot'],string>>={reel:'Récupère le fil et laisse sortir du fil au frein.',elastic:'Absorbe la charge sur une ligne fixe.',main_line:'Relie la canne au montage.',leader:'Segment remplaçable avant l’hameçon.',tippet:'Pointe fine portant la mouche.',float:'Porte les lests et rend la touche visible.',weight:'Règle la descente et la tenue du montage.',bait:'Esche proposée aux poissons compatibles.',lure:'Imitation animée par les gestes et la récupération.',fly:'Imitation portée par le montage et le courant.',feeder:'Diffuse une portion d’amorce après dépôt.',groundbait:'Attire localement les candidats déjà compatibles.',landing:'Limite la taille recevable ; ne capture pas automatiquement.'};
 const effects:string[]=[];if(i.strength!==undefined)effects.push('Résistance de jeu '+i.strength+' : contrôle et maillon faible.');if(i.control!==undefined)effects.push('Contrôle '+i.control+' : '+(i.slot==='elastic'?'compliance de l’élastique.':'traction et récupération.'));if(i.slot==='float')effects.push('Portance '+i.capacity+' g, lest intégré '+(i.integrated??0)+' g.');else if(i.mass!==undefined)effects.push('Masse de jeu '+i.mass+' g : descente selon la recette.');if(i.slot==='landing')effects.push('Gabarit maximal '+i.capacity+' cm.');if(i.slot==='feeder')effects.push('Diffusion du feeder '+(i.diffusion??35)+' s.');if(i.slot==='groundbait')effects.push('Amorçage local : 45 s ; après dissolution du PVA : '+(i.diffusion??35)+' s. Candidats déjà compatibles.');if(i.retention!==undefined)effects.push('Tenue '+Math.round(i.retention*100)+' % : une animation forte peut laver une esche fragile.');
 const trade=i.slot==='elastic'?'Plus de souplesse absorbe la charge mais donne davantage de débattement.':i.slot==='reel'?'Un frein ouvert protège la ligne mais laisse partir du fil.':i.strength!==undefined?'La finesse favorise la discrétion ; une résistance faible limite le contrôle.':i.slot==='float'?'Un excès de plombée immerge le signal ; un flotteur trop peu chargé reste essayable.':i.slot==='weight'||i.slot==='feeder'?'Une descente rapide change les couches prospectées et la présentation.':i.slot==='landing'?'Vérifiez le gabarit avant de viser une grande prise.':i.slot==='groundbait'?'Les portions payantes sont consommées immédiatement, sans garantir de rencontre.':i.consumable!==false&&['bait','fly'].includes(i.slot)?'Une portion utilisée est consommée ; le régime limite les poissons candidats.':'La recette détermine sa fixation et ce qui sera détaché en cas de casse.';
 return {role:roles[i.slot]??i.description,effects:effects.length?effects:[i.description],use:i.methods.join(' · '),trade};
}
export function exposedCost(c:RigConfig){return slotsFor(c.method,c.recipe,c.technique).reduce((sum,slot)=>{const i=component(c.components[slot]??'');return sum+(i&&!i.free&&!['reel','landing','clonk','backing'].includes(slot)&&!(slot==='elastic'&&c.method==='pole')?quantityFor(c,slot)*i.price/i.pack:0);},0);}
export function missingComponents(t:Tackle,c:RigConfig){return slotsFor(c.method,c.recipe,c.technique).flatMap(slot=>{const i=component(c.components[slot]??'');if(!i)return [{slot,id:'',quantity:0,price:0}];const quantity=Math.max(0,quantityFor(c,slot)-available(t,i.id));return quantity>1e-8?[{slot,id:i.id,quantity,price:Math.ceil(quantity/i.pack)*i.price}]:[];});}
/** Même moteur et mêmes composants que la ligne en pêche ; aucun second rendu 3D. */
export function rigPreview(c:RigConfig,waterDepth:number,seconds=6,current=0){const s=initialPresentation();const rows=[];for(let n=0;n<seconds*60;n++){stepPresentation(c,s,{dt:1/60,waterDepth,reelSpeed:0,lift:.5,current,wind:0,restrained:false,boatSpeed:0,boatTurn:0,clonk:false});if(n%30===0)rows.push({time:n/60,depth:s.depth,x:s.point.x});}const f=component(c.components.float??'');return {rows,depth:s.depth,waterDepth,load:floatLoad(c),capacity:f?.capacity,engine:techniqueFor(c).engine,drift:s.point.x};}
