import {buyShopProduct,equipShopRod} from './helpers';
import {ensureLegacyProfile} from './helpers';
import { openMenuPage } from './helpers';
import { test, expect } from '@playwright/test';
import {legacySave as emptySave} from '../support/legacy';
import {recordCatch} from '../../src/game/save';
import { SPECIES } from '../../src/game/catalog';
test('Spécimens, photo locale, boutique, filtres et export sans doubler les gains', async ({ page }, info) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  const seed = emptySave();
  for (let i = 0; i < 5; i++) recordCatch(seed, { id: `known-${i}`, speciesId: 'roach', length: 20 + i, date: '2026-10-01T10:00:00Z' });
  await page.addInitScript(data => { if (!localStorage.getItem('au-fil-de-leau.save.v1')) localStorage.setItem('au-fil-de-leau.save.v1', JSON.stringify(data)); }, seed);
  await ensureLegacyProfile(page); await page.goto('/'); await expect(page.locator('body')).toHaveAttribute('data-ready', 'true');
  await openMenuPage(page, 'shop-open'); await buyShopProduct(page,'balanced'); await page.locator('#purchase-yes').click(); await equipShopRod(page,'balanced');
  await expect(page.locator('[data-shop-product="balanced"]')).toContainText('Équipé'); await page.screenshot({ path: `test-results/${info.project.name}-shop.png` });
  await page.locator('[data-close="shop"]').click(); await openMenuPage(page, 'collection-open');
  await expect(page.locator('.specimen-card')).toHaveCount(5); await page.locator('[data-favorite="known-0"]').click();
  await page.locator('[data-specimen="known-0"]').click(); await expect(page.locator('#fish-preview')).toHaveAttribute('data-loaded', 'true');
  await expect(page.locator('#photo-state')).toContainText('Photo conservée'); await page.locator('#release-fish').click();
  await page.locator('[data-close="collection"]').click(); await page.reload(); await expect(page.locator('body')).toHaveAttribute('data-ready', 'true');
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('au-fil-de-leau.save.v1')!));
  expect(stored.total).toBe(5); expect(stored.xp).toBe(seed.xp); expect(stored.coins).toBe(seed.coins - 70); expect(stored.equipped).toBe('balanced'); expect(stored.favorites).toEqual(['known-0']);
  await openMenuPage(page, 'collection-open'); await expect(page.locator('[data-photo="known-0"] img')).toBeVisible();
  await page.screenshot({ path: `test-results/${info.project.name}-journal.png` }); await page.locator('[data-close="collection"]').click();
  await openMenuPage(page, 'dex-open'); await page.locator('#dex-filters').evaluate((e:HTMLDetailsElement)=>e.open=true);await page.locator('#dex-state').selectOption('playable'); await expect(page.locator('.dex-tile')).toHaveCount(SPECIES.filter(s=>s.mode==='capture').length);
  await page.locator('#dex-search').fill('gardon'); await expect(page.locator('.dex-tile')).toHaveCount(1); await page.locator('.dex-tile').click();
  await page.screenshot({ path: `test-results/${info.project.name}-encyclopedia.png` }); expect(errors).toEqual([]);
});
