import {techniqueConfig} from '../../src/game/rig';
import {test,expect} from '@playwright/test';
import {emptySave} from '../../src/game/save';
import {xpThreshold} from '../../src/game/curriculum';
import {mkdir} from 'node:fs/promises';
test('Familles, prêt et retour préservent le carnet normal',async({page},info)=>{const s=emptySave();s.xp=xpThreshold(5);await page.addInitScript(s=>{if(!localStorage.getItem('au-fil-de-leau.save.v1'))localStorage.setItem('au-fil-de-leau.save.v1',JSON.stringify(s));localStorage.setItem('au-fil-de-leau.gestures.v3','3');},s);await page.goto('/');await expect(page.locator('body')).toHaveAttribute('data-ready','true');await page.locator('#menu-open').click();await page.locator('#progress-open').click();await expect(page.locator('#family-journey')).toContainText('Exploration');await page.locator('#family-journey details').filter({hasText:'Exploration'}).locator('summary').click();await mkdir('docs/apercus/gameplay-progression',{recursive:true});await page.screenshot({path:`docs/apercus/gameplay-progression/lot1-${info.project.name}.png`});await page.locator('[data-learning="exploration"]').click();await expect(page.locator('#learning-exit')).toBeVisible();const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('au-fil-de-leau.save.v1')!));expect(before.total).toBe(0);expect(before.development).toBeUndefined();await page.locator('#learning-exit').click();await expect(page.locator('#learning-exit')).toHaveCount(0);const after=await page.evaluate(()=>JSON.parse(localStorage.getItem('au-fil-de-leau.save.v1')!));expect(after.inventory).toEqual(before.inventory);expect(after.coins).toBe(before.coins);expect(after.total).toBe(0);});

test('Atelier : annuler, appliquer et recharger sans dupliquer le stock',async({page},info)=>{const s=emptySave();s.tackle.stock['light-shot']=5;await page.addInitScript(s=>{if(!localStorage.getItem('au-fil-de-leau.save.v1'))localStorage.setItem('au-fil-de-leau.save.v1',JSON.stringify(s));localStorage.setItem('au-fil-de-leau.gestures.v3','3');},s);await page.goto('/');await expect(page.locator('body')).toHaveAttribute('data-ready','true');await page.locator('#prepare-open').click();await page.locator('[data-work-rig]').first().click();await page.locator('#rig-depth').fill('1.5');await page.locator('#rig-depth').dispatchEvent('change');await page.locator('#rig-cancel').click();let saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('au-fil-de-leau.save.v1')!));expect(saved.tackle.config.depth).toBe(1);await page.locator('[data-work-rig]').first().click();await page.locator('.line-part[data-rig-part="weight"]').click();await page.locator('#rig-component').selectOption('light-shot');await page.locator('#rig-connect').click();await page.locator('#rig-position').fill('0.15');await page.locator('#rig-position').dispatchEvent('change');await page.locator('#rig-zoom').selectOption('4');await expect(page.locator('#rig-position')).toHaveValue('0.15');await page.screenshot({path:`docs/apercus/gameplay-progression/lot2-${info.project.name}.png`});await page.locator('#rig-done').click();saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('au-fil-de-leau.save.v1')!));expect(saved.tackle.stock['light-shot']).toBe(5);expect(saved.tackle.config.positions.weight.metres).toBe(.15);await page.reload();await expect(page.locator('body')).toHaveAttribute('data-ready','true');saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('au-fil-de-leau.save.v1')!));expect(saved.tackle.stock['light-shot']).toBe(5);expect(saved.tackle.config.positions.weight.metres).toBe(.15);expect(await page.locator('body').evaluate(e=>e.scrollWidth<=innerWidth)).toBe(true);});

test.beforeEach(async({context})=>{const token=process.env.VERCEL_OIDC_TOKEN;if(token&&process.env.GAME_URL){const origin=new URL(process.env.GAME_URL).origin;await context.route(`${origin}/**`,route=>route.continue({headers:{...route.request().headers(),'x-vercel-trusted-oidc-idp-token':token}}));}});
test('Aperçu de méthode et plombs multiples : annulation, coût, zoom et sauvegarde',async({page},info)=>{
 const s=emptySave();s.xp=xpThreshold(15);s.tackle.config=techniqueConfig('coup');s.tackle.stock['light-shot']=5;await page.addInitScript(s=>{if(!localStorage.getItem('au-fil-de-leau.save.v1'))localStorage.setItem('au-fil-de-leau.save.v1',JSON.stringify(s));localStorage.setItem('au-fil-de-leau.gestures.v3','3');},s);
 await page.goto('/');await expect(page.locator('body')).toHaveAttribute('data-ready','true');await page.locator('#prepare-open').click();await page.locator('[data-work-rig]').first().click();await page.locator('.line-part[data-rig-part="weight"]').click();await page.locator('#rig-component').selectOption('light-shot');await page.locator('#rig-connect').click();await page.locator('#rig-shot-start').click();await page.locator('#rig-shot-add').click();await page.locator('#rig-shot-add').click();await page.locator('[data-shot-select="0"]').check();await page.locator('[data-shot-select="1"]').check();await page.locator('#rig-shot-target').fill('0.5');await page.locator('#rig-shot-target').dispatchEvent('change');await page.locator('#rig-zoom').selectOption('4');await page.screenshot({path:`docs/apercus/gameplay-progression/lot5-plombs-${info.project.name}.png`});await page.locator('#rig-done').click();let saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('au-fil-de-leau.save.v1')!));expect(saved.tackle.config.shots).toHaveLength(3);expect(saved.tackle.stock['light-shot']).toBe(5);
 await page.locator('[data-slot="rod"]').click();await page.locator('[data-choose-rod="starter"]').click();await page.locator('[data-choose-technique="leurre"]').click();await expect(page.locator('#method-apply')).toBeVisible();saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('au-fil-de-leau.save.v1')!));expect(saved.tackle.config.technique).toBe('coup');await page.locator('#method-cancel').click();await page.locator('[data-choose-technique="leurre"]').click();await page.locator('#method-apply').click();saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('au-fil-de-leau.save.v1')!));expect(saved.tackle.config.technique).toBe('leurre');expect(saved.tackle.stock['light-shot']).toBe(5);await page.reload();await expect(page.locator('body')).toHaveAttribute('data-ready','true');expect(await page.locator('body').evaluate(e=>e.scrollWidth<=innerWidth)).toBe(true);
});

test('Progression accélérée séparée et exercice repris après rechargement',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('au-fil-de-leau.gestures.v3','3'));await page.goto('/');await expect(page.locator('body')).toHaveAttribute('data-ready','true');const original=await page.evaluate(()=>localStorage.getItem('au-fil-de-leau.save.v1'));
 await page.locator('#menu-open').click();await page.locator('#help-open').click();await page.locator('#test-open').click();await page.locator('#test-toggle').click();await expect(page.locator('#test-badge')).toBeVisible();await expect(page.locator('body')).toHaveAttribute('data-ready','true');await page.locator('#menu-open').click();await page.locator('#help-open').click();await page.locator('#test-open').click();await page.locator('#test-rules').click();await expect(page.locator('body')).toHaveAttribute('data-ready','true');await page.locator('#menu-open').click();await page.locator('#help-open').click();await page.locator('#test-open').click();await page.locator('#test-level').fill('5');await page.locator('#test-level-apply').click();for(const id of ['test-tools','help','menu'])await page.locator(`[data-close="${id}"]`).click();await page.locator('#menu-open').click();await page.locator('#progress-open').click();await expect(page.locator('#family-journey')).toContainText('niveau 5');await page.locator('#family-journey details').filter({hasText:'Bordure'}).first().locator('summary').click();await page.locator('[data-learning="bordure"]').click();await expect(page.locator('#learning-step')).toContainText('Ajuster la profondeur');await page.locator('#prepare-open').click();await page.locator('[data-work-rig]').first().click();await page.locator('#rig-depth').fill('1.5');await page.locator('#rig-depth').dispatchEvent('change');await page.locator('#rig-done').click();await page.locator('[data-close="preparation"]').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('au-fil-de-leau.test.save.v1')!).curriculum.quests.bordure?.steps.includes('depth'));await page.locator('#learning-exit').click();await page.reload();await expect(page.locator('body')).toHaveAttribute('data-ready','true');const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('au-fil-de-leau.test.save.v1')!));expect(saved.curriculum.quests.bordure.steps).toEqual(['depth']);expect(saved.development.kind).toBe('rules');expect(saved.coins).toBe(0);expect(saved.inventory).toEqual(['starter','pole-starter']);expect(await page.evaluate(()=>localStorage.getItem('au-fil-de-leau.save.v1'))).toBe(original);
});
