import {receiveByGesture} from './helpers';
import {test,expect,type Page} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import {castByGesture,timedCastGesture,chooseMethod,openMenuPage,holdMouseReel} from './helpers';
import {oldV4} from '../support/legacy';
const folder='docs/apercus/mobile-materiel/regression';
const snapshot=(page:Page)=>page.evaluate(()=>(window as any).__fishingQA.snapshot());
async function boot(page:Page){await page.addInitScript(()=>{Math.random=()=>0;localStorage.setItem('au-fil-de-leau.gestures.v3','3');});await page.goto('/');await expect(page.locator('body')).toHaveAttribute('data-ready','true');await page.evaluate(()=>(window as any).__fishingQA.pauseSimulation());}
async function preciseCast(page:Page){await timedCastGesture(page,600,.5);await expect(page.locator('body')).toHaveAttribute('data-phase','casting');const {target}=await snapshot(page);expect(Math.hypot(target.x,target.z-3.2)).toBeLessThanOrEqual(1.2);}
async function catchPole(page:Page){await preciseCast(page);await page.evaluate(()=>(window as any).__fishingQA.advance(30));await page.locator('#strike').click();await expect(page.locator('#reel-control')).toBeHidden();const line=(await snapshot(page)).lineLength;await page.evaluate(()=>(window as any).__fishingQA.advance(150,'smart'));await receiveByGesture(page);await expect(page.locator('#caught')).toBeVisible();await expect(page.locator('#fish-preview')).toHaveAttribute('data-loaded','true');expect((await snapshot(page)).lineLength).toBe(line);}

test('Nouvelle partie, trois vues dans la même scène, carte, cercle et occupation lisible',async({page},info)=>{
 await mkdir(folder,{recursive:true});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await boot(page);
 const before=await snapshot(page);expect(before.method).toBe('pole');expect(before.rights.posts).toHaveLength(3);expect(before.hasReel).toBe(false);
 await page.waitForTimeout(500);await page.screenshot({path:`${folder}/after-${info.project.name}-lake.png`});
 await page.locator('#map-open').click();await expect(page.locator('#map [data-post]')).toHaveCount(15);await page.locator('#map [data-post="reed-bank"]').click();await expect(page.locator('#post-sheet')).toContainText('Niveau 3 OU 2');await expect(page.locator('#post-select')).toBeDisabled();await page.screenshot({path:`${folder}/${info.project.name}-map.png`});
 const cameras=[];
 for(const post of ['cove','bank','jetty','cove','bank','jetty']){
  await page.locator(`#map [data-post="${post}"]`).click();if((await snapshot(page)).post===post)continue;await page.locator('#post-select').click();const s=await snapshot(page);expect(s.post).toBe(post);expect(s.engines).toBe(before.engines);expect(s.sceneId).toBe(before.sceneId);expect(s.totalMeshes).toBe(before.totalMeshes);cameras.push(s.camera);await page.waitForTimeout(120);await page.screenshot({path:`${folder}/${info.project.name}-${post}.png`});await page.locator('#map-open').click();
 }
 expect(new Set(cameras.map(c=>JSON.stringify(c))).size).toBe(3);await page.locator('#map [data-post="point"]').click();await expect(page.locator('#post-sheet')).toContainText('Niveau 6 OU 6');await expect(page.locator('#post-select')).toBeDisabled();await page.locator('[data-close="map"]').click();
 await page.locator('#prepare-open').click();await expect(page.locator('[data-slot="elastic"]')).toBeVisible();await expect(page.locator('[data-slot="reel"]')).toHaveCount(0);await page.screenshot({path:`${folder}/after-${info.project.name}-material.png`});await page.locator('[data-work-rig]').first().click();await page.locator('#rig-depth').fill('0.5');await page.locator('#rig-depth').dispatchEvent('change');await expect(page.locator('#rig-depth')).toHaveValue('0.5');await page.screenshot({path:`${folder}/${info.project.name}-rig.png`});await page.locator('#rig-done').click();await page.locator('[data-work-tab="bag"]').click();await page.locator('#bag-search').fill('flotteur');expect(await page.locator('#bag-items .compact-row').count()).toBeGreaterThanOrEqual(1);await page.locator('[data-close="preparation"]').click();
 await castByGesture(page);await expect(page.locator('#map-open')).toBeHidden();await openMenuPage(page,'locations-open');await page.locator('#open-pond-map').click();await page.locator('#map [data-post="cove"]').click();await page.locator('#post-select').click();await expect(page.locator('#post-warning')).toContainText('Ramenez');expect((await snapshot(page)).post).toBe('jetty');const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('au-fil-de-leau.save.v1')!));expect(saved.tackle.active.resolved).toBe(false);expect(errors).toEqual([]);
});

test('Migration navigateur v4 : copie originale, droits acquis et préférences mobiles explicitement persistantes',async({page})=>{
 const seed=oldV4();seed.coins=100;seed.inventory.push('balanced');seed.equipped='balanced';seed.tackle.stock.corn=12;
 await page.addInitScript(s=>{if(!localStorage.getItem('au-fil-de-leau.save.v1'))localStorage.setItem('au-fil-de-leau.save.v1',JSON.stringify(s));},seed);await boot(page);
 const saved=await page.evaluate(()=>({current:JSON.parse(localStorage.getItem('au-fil-de-leau.save.v1')!),backup:JSON.parse(localStorage.getItem('au-fil-de-leau.save.before-v7')!)}));expect(saved.backup).toEqual(seed);expect(saved.current.progression.methods).toEqual(['pole','float','lure','bottom']);expect(saved.current.equipped).toBe('balanced');expect(saved.current.coins).toBe(100);expect(saved.current.tackle.stock.corn).toBe(12);
 await openMenuPage(page,'help-open');const download=page.waitForEvent('download');await page.locator('#export-before-progression').click();const file=await download;expect(file.suggestedFilename()).toContain('avant-progression');await page.locator('#control-side').selectOption('right');await page.locator('#control-single').check();await page.reload();await expect(page.locator('body')).toHaveAttribute('data-ready','true');const next=await page.evaluate(()=>JSON.parse(localStorage.getItem('au-fil-de-leau.save.v1')!));expect(next.settings.controls).toMatchObject({side:'right',singleFinger:true});expect(next.total).toBe(0);
});

test('Deux vraies captures au coup ouvrent définitivement le poste, première prise puis initiation aux leurres',async({page},info)=>{
 await boot(page);await catchPole(page);await expect(page.locator('#catch-progression')).toContainText('initiation');await page.locator('#release-fish').click();await catchPole(page);await expect(page.locator('#catch-progression')).toContainText('définitivement');await page.locator('#release-fish').click();
 expect((await snapshot(page)).rights.precision).toBe(2);await page.reload();await expect(page.locator('body')).toHaveAttribute('data-ready','true');await page.evaluate(()=>(window as any).__fishingQA.pauseSimulation());
 await page.locator('#map-open').click();await page.locator('#map [data-post="reed-bank"]').click();await expect(page.locator('#post-sheet')).toContainText('La place est à toi');await expect(page.locator('#post-select')).toBeEnabled();await page.screenshot({path:`${folder}/${info.project.name}-reeds-unlocked.png`});await page.locator('#map [data-post="bank"]').click();await page.locator('#post-select').click();
 await page.locator('#prepare-open').click();await page.locator('[data-work-rig]').first().click();await page.locator('#rig-depth').fill('0.4');await page.locator('#rig-depth').dispatchEvent('change');await page.locator('#rig-done').click();await page.locator('[data-slot="method"]').click();await expect(page.locator('[data-choose-method="lure"]')).toBeDisabled();await page.locator('#start-lure-initiation').click();await page.locator('#initiation-complete').click();await chooseMethod(page,'lure');await page.locator('[data-work-rig]').first().click();await expect(page.locator('.rig-float')).toHaveCount(0);await expect(page.locator('.rig-lure')).toBeVisible();await page.locator('#rig-done').click();await chooseMethod(page,'pole');await page.locator('[data-work-rig]').first().click();await expect(page.locator('#rig-depth')).toHaveValue('0.4');await page.locator('#rig-done').click();await chooseMethod(page,'lure');await page.locator('[data-close="preparation"]').click();
 await castByGesture(page);await page.evaluate(()=>(window as any).__fishingQA.advance(12));expect((await snapshot(page)).phase).toBe('waiting');expect((await snapshot(page)).presentationDepth).toBeGreaterThan(.5);await expect(page.locator('#retrieve-setting')).toBeVisible();await page.locator('#retrieve-speed').selectOption('0.8');await holdMouseReel(page);await page.evaluate(()=>(window as any).__fishingQA.advance(20));await page.mouse.up();await expect(page.locator('body')).toHaveAttribute('data-phase','bite');await page.locator('#strike').click();await expect(page.locator('#reel-control')).toBeVisible();await page.evaluate(()=>(window as any).__fishingQA.advance(150,'smart'));await receiveByGesture(page);await expect(page.locator('#caught')).toBeVisible();const save=await page.evaluate(()=>JSON.parse(localStorage.getItem('au-fil-de-leau.save.v1')!));expect(save.journal.at(-1).method).toBe('lure');expect(save.version).toBe(7);
});

test('Mesures des postes : ressources partagées et relevé du rendu réel disponible',async({page},info)=>{
 await boot(page);const results=[];
 for(const post of ['jetty','cove','bank']){if(post!=='jetty'){await page.locator('#map-open').click();await page.locator(`#map [data-post="${post}"]`).click();await page.locator('#post-select').click();}const start=await page.evaluate(()=>({at:performance.now(),...(window as any).__fishingQA.snapshot()}));const samples=[];for(let i=0;i<20;i++){await page.waitForTimeout(150);samples.push(await page.evaluate(()=>({at:performance.now(),...(window as any).__fishingQA.snapshot(),render:(window as any).__fishingQA.rendering()})));}const last=samples.at(-1)!;const cpu=samples.map(s=>s.render.cpuFrameMs).sort((a,b)=>a-b);results.push({post,fps:(last.lakeFrames-start.lakeFrames)/((last.at-start.at)/1000),cpuMedianMs:cpu[10],cpuP95Ms:cpu[18],...last.render});}
 await writeFile(`${folder}/${info.project.name}-performance.json`,JSON.stringify({viewport:page.viewportSize(),renderer:'Chromium / SwiftShader, pas un téléphone réel',results},null,2));
});

test('Accrochage réel au coup : commande de canne disponible pendant attente et libération tactile',async({page})=>{
 await boot(page);await page.locator('#map-open').click();await page.locator('#map [data-post="cove"]').click();await page.locator('#post-select').click();
 const {width:w,height:h}=page.viewportSize()!;await page.mouse.move(w*.45,h*.8);await page.mouse.down();await page.mouse.move(w*.56,h*.45,{steps:8});await page.mouse.up();await expect(page.locator('body')).toHaveAttribute('data-phase','casting');await page.evaluate(()=>(window as any).__fishingQA.advance(2.3));expect((await snapshot(page)).snagged).toBe(true);await expect(page.locator('#rod-control')).toBeVisible();
 const b=(await page.locator('#rod-control').boundingBox())!;await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2-90,b.y+b.height/2+70);await page.mouse.up();await page.evaluate(()=>(window as any).__fishingQA.advance(.12));const pose=await snapshot(page);expect(pose.lift,JSON.stringify(pose)).toBeLessThanOrEqual(.35);expect(Math.abs(pose.yaw-pose.direction),JSON.stringify(pose)).toBeGreaterThanOrEqual(.45);await page.locator('#snag-release').click();expect((await snapshot(page)).snagged).toBe(false);expect((await snapshot(page)).phase).toBe('waiting');await page.locator('#cancel-cast').click();expect((await snapshot(page)).phase).toBe('idle');
});
