import {test,expect} from '@playwright/test';
import {emptySave,recordCatch,recordObservation} from '../../src/game/save';
import {SPECIES} from '../../src/game/catalog';
import {fishRoutes} from '../../src/game/fish-access';
import {ObservationSession} from '../../src/game/observations';
import {openMenuPage} from './helpers';
const key='au-fil-de-leau.save.v1';
const fixture=()=>{const s=emptySave();for(let i=0;i<6;i++)recordCatch(s,{id:'memory-'+i,speciesId:i===3?'perch':'roach',length:18+i,date:`2026-10-0${i+1}T12:00:00Z`,method:'pole'});s.favorites=s.journal.slice(0,5).map(f=>f.id);s.coins=500;return s;};
async function boot(page:any,s=emptySave()){await page.addInitScript(({s,key}:{s:any,key:string})=>{localStorage.setItem('au-fil-de-leau.gestures.v3','3');if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify(s));},{s,key});await page.goto('/');await expect(page.locator('body')).toHaveAttribute('data-ready','true');}
test('Lot 04 : souvenirs, recherche combinée, favori, remplacement et recharge',async({page},info)=>{
 await boot(page,fixture());await openMenuPage(page,'collection-open');await expect(page.locator('[data-specimen]')).toHaveCount(6);
 await page.locator('#journal-query').fill('inexistant');await expect(page.locator('#journal-list')).toContainText('Aucun souvenir avec ces filtres');await page.locator('[data-journal-reset]').click();
 await page.locator('#journal-query').fill('gardon');await page.locator('#journal-sort').selectOption('length');await expect(page.locator('[data-specimen]').first()).toHaveAttribute('data-specimen','memory-5');await page.locator('[data-clear-filter="journal-query"]').click();
 await page.locator('[data-specimen="memory-5"]').click();await expect(page.locator('#fish-preview')).toHaveAttribute('data-loaded','true');await page.locator('#release-fish').click();await expect(page.locator('#journal-sort')).toHaveValue('length');
 await page.screenshot({path:`docs/apercus/refonte-ui/04-apres/${info.project.name}-carnet-avance.png`});await page.locator('[data-close="collection"]').click();await openMenuPage(page,'aquarium-open');await expect(page.locator('#aquarium-canvas')).toHaveAttribute('data-loaded','true');await page.locator('#aq-fish-open').click();
 await page.locator('[data-aq-choose="memory-5"]').click();await page.locator('#aquarium-add').click();expect(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)!).favorites,key)).not.toContain('memory-5');await expect(page.locator('#aq-selection')).toContainText('Bassin plein');
 await page.locator('#aq-replace-slot').selectOption('0');await page.locator('#aq-replace').click();await expect.poll(()=>page.evaluate(k=>JSON.parse(localStorage.getItem(k)!).favorites[0],key)).toBe('memory-5');expect(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)!).journal.length,key)).toBe(6);
 await page.screenshot({path:`docs/apercus/refonte-ui/04-apres/${info.project.name}-aquarium-poissons.png`});await page.locator('[data-aq-remove="memory-5"]').click();await page.locator('[data-close="aquarium-fish"]').click();await page.locator('#aq-decor-open').click();await expect(page.locator('#aq-plants')).toBeDisabled();await page.locator('#aq-shop').click();await expect(page.locator('#shop-family')).toHaveValue('decor');await page.locator('#shop [data-buy="plants"]').click();await page.locator('#purchase-yes').click();await page.locator('[data-close="shop"]').click();await expect(page.locator('#aq-plants')).toBeEnabled();await page.locator('#aq-plants').check();await page.locator('[data-close="aquarium-decor"]').click();
 await expect(page.locator('#aquarium-canvas')).toHaveAttribute('data-loaded','true');await page.screenshot({path:`docs/apercus/refonte-ui/04-apres/${info.project.name}-aquarium-avance.png`});await page.locator('[data-close="aquarium"]').click();await expect.poll(()=>page.evaluate(()=>(window as any).__fishingQA.snapshot().engines)).toBe(1);await page.reload();await expect(page.locator('body')).toHaveAttribute('data-ready','true');const after=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)!),key);expect(after.journal).toHaveLength(6);expect(after.favorites).not.toContain('memory-5');expect(after.aquarium.plants).toBe(true);
});
test('Lot 04 : vide, réglages persistants, import protégé et aide contextuelle',async({page},info)=>{
 await boot(page);await openMenuPage(page,'collection-open');await expect(page.locator('#journal-list')).toContainText('Ton premier souvenir');await page.locator('[data-journal-tab="observations"]').click();await expect(page.locator('#observation-journal')).toContainText('Aucune observation');await page.locator('#journal-save-link').click();
 await page.locator('#control-side').selectOption('right');await page.locator('#control-single').check();const before=await page.evaluate(k=>localStorage.getItem(k),key);await page.locator('#save-file').setInputFiles({name:'invalide.json',mimeType:'application/json',buffer:Buffer.from('{"version":999}')});await expect(page.locator('#toast')).toContainText('Format de sauvegarde');expect(await page.evaluate(k=>localStorage.getItem(k),key)).toBe(before);
 const incoming=fixture();await page.locator('#save-file').setInputFiles({name:'valide.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(incoming))});await expect(page.locator('#import-review')).toBeVisible();expect(await page.evaluate(k=>localStorage.getItem(k),key)).toBe(before);await page.locator('#cancel-import').click();
 const download=page.waitForEvent('download');await page.locator('#export-save').click();expect((await download).suggestedFilename()).toContain('normal');await page.screenshot({path:`docs/apercus/refonte-ui/04-apres/${info.project.name}-reglages.png`});await page.locator('[data-close="settings"]').click();await page.locator('[data-close="collection"]').click();await openMenuPage(page,'help-open');await page.locator('[data-lesson="combat"]').click();await expect(page.locator('#lesson-body')).toContainText('Canne à droite');await page.locator('[data-close="lesson-sheet"]').click();await page.locator('[data-lesson="techniques"]').click();await expect(page.locator('[data-help-technique]')).toHaveCount(22);await page.locator('[data-help-technique="bolognaise"]').click();await expect(page.locator('#lesson-body')).toContainText('Retenir');await page.locator('[data-close="lesson-sheet"]').click();await page.locator('[data-close="help"]').click();await page.locator('[data-close="menu"]').click();await page.locator('#prepare-open').click();await page.locator('[data-work-rig]').first().click();await page.locator('[data-slot="bait"]').click();await page.locator('[data-component-info="kit-worm"]').click();await page.locator('[data-help-component="kit-worm"]').click();await page.locator('[data-close="lesson-sheet"]').click();await expect(page.locator('#component-detail-title')).toContainText('Ver');await expect(page.locator('[data-help-component="kit-worm"]')).toBeFocused();
 await page.reload();await expect(page.locator('body')).toHaveAttribute('data-ready','true');await openMenuPage(page,'settings-open');await expect(page.locator('#control-side')).toHaveValue('right');await expect(page.locator('#control-single')).toBeChecked();
 for(const [width,height]of [[320,740],[390,844],[430,932],[844,390]]){await page.setViewportSize({width,height});expect(await page.locator('#settings').evaluate(e=>e.scrollWidth<=e.clientWidth+1)).toBe(true);await page.screenshot({path:`docs/apercus/refonte-ui/04-apres/${info.project.name}-${width}-reglages.png`});}
});
test('Lot 04 : erreur WebGL, favoris 2D et menus accessibles',async({page},info)=>{
 await page.addInitScript(()=>{const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type:any,...args:any[]){if(type==='webgl'||type==='webgl2'||type==='experimental-webgl')return null;return (get as any).call(this,type,...args); } as any;});await page.addInitScript(({s,key})=>localStorage.setItem(key,JSON.stringify(s)),{s:fixture(),key});await page.goto('/');await expect(page.locator('#loading-menu')).toBeVisible();await page.locator('#loading-menu').click();await page.locator('#aquarium-open').click();await expect(page.locator('#aquarium-state')).toContainText('3D indisponible');await page.locator('#aq-retry').click();await page.locator('#aq-fish-open').click();await expect(page.locator('[data-aq-view]')).toHaveCount(5);expect(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)!).favorites.length,key)).toBe(5);await page.screenshot({path:`docs/apercus/refonte-ui/04-apres/${info.project.name}-aquarium-erreur-2d.png`});await page.locator('[data-close="aquarium-fish"]').click();await page.locator('[data-close="aquarium"]').click();await expect(page.locator('#menu')).toBeVisible();
});
test('Lot 04 : observation distincte, image absente, réduction des mouvements et import confirmé',async({page})=>{
 const s=fixture(),fish=SPECIES.find(f=>f.mode==='observation')!,route=fishRoutes(fish.id)[0],session=new ObservationSession(route.post,fish.id,127,()=>.6);session.holding=true;for(let n=0;n<300;n++)session.step(.05);recordObservation(s,session.specimen);
 await page.emulateMedia({reducedMotion:'reduce'});await page.route('**/fishdex-assets/**',r=>r.abort());await boot(page,s);await openMenuPage(page,'collection-open');await page.locator('[data-journal-tab="observations"]').click();await expect(page.locator('[data-observation]')).toHaveCount(1);await expect(page.locator('#observation-journal .image-fallback')).toBeVisible();expect(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)!).favorites.length,key)).toBe(5);
 await page.locator('#journal-query').fill('inexistant');await expect(page.locator('#observation-journal')).toContainText('Aucun souvenir avec ces filtres');await page.locator('[data-journal-reset]').filter({visible:true}).click();await expect(page.locator('[data-observation]')).toHaveCount(1);await page.locator('#journal-save-link').click();const incoming=emptySave();await page.locator('#save-file').setInputFiles({name:'nouvelle.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(incoming))});await page.locator('#confirm-import').click();await expect.poll(()=>page.evaluate(k=>JSON.parse(localStorage.getItem(k)!).total,key)).toBe(0);await page.reload();await expect(page.locator('body')).toHaveAttribute('data-ready','true');expect(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)!).observations.length,key)).toBe(0);
});
