import {test,expect,type Page} from '@playwright/test';
import {emptySave,recordCatch} from '../../src/game/save';
import {SHOP_PRODUCTS,SHOP_DEPARTMENTS,shopCompatible} from '../../src/game/shop';
import {openMenuPage} from './helpers';
const key='au-fil-de-leau.save.v1';
const rich=()=>{const s=emptySave();s.coins=500;s.xp=10000;return s;};
async function boot(page:Page,save=emptySave()){
 await page.addInitScript(s=>{localStorage.setItem('au-fil-de-leau.gestures.v3','3');if(!localStorage.getItem('au-fil-de-leau.save.v1'))localStorage.setItem('au-fil-de-leau.save.v1',JSON.stringify(s));},save);
 await page.goto('/');await expect(page.locator('body')).toHaveAttribute('data-ready','true');
}
async function product(page:Page,id:string){await page.locator('#shop-query').fill(SHOP_PRODUCTS.find(p=>p.id===id)!.name);await page.locator(`[data-shop-product="${id}"]`).click();}
test.beforeEach(async({context})=>{const token=process.env.VERCEL_OIDC_TOKEN;if(token&&process.env.GAME_URL){const origin=new URL(process.env.GAME_URL).origin;await context.route(`${origin}/**`,route=>route.continue({headers:{...route.request().headers(),'x-vercel-trusted-oidc-idp-token':token}}));}});

test('Boutique : accueil compact, six rayons réels, aquarium séparé et dispositions',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await boot(page);await openMenuPage(page,'shop-open');
 await expect(page.locator('.shop-department')).toHaveCount(6);await expect(page.locator('.shop-product')).toHaveCount(0);
 await expect(page.locator('.shop-aquarium [data-shop-department]')).toHaveCount(1);
 await expect(page.locator('#shop-balance')).toContainText('0 écus');
 for(const d of SHOP_DEPARTMENTS){await page.locator(`[data-shop-department="${d.id}"]`).click();await expect(page.locator('.shop-product').first()).toBeVisible();await expect(page.locator('[data-shop-product="plants"]')).toHaveCount(0);if(await page.locator('[data-shop-group]').count())for(const g of await page.locator('[data-shop-group]').evaluateAll(es=>es.map(e=>(e as HTMLElement).dataset.shopGroup!))){await page.locator(`[data-shop-group="${g}"]`).click();await expect(page.locator('.shop-product').first()).toBeVisible();}await page.locator('[data-shop-back]').click();}
 for(const [width,height] of info.project.name==='mobile'?[[320,740],[390,844],[430,932],[844,390]]:[[1440,900]]){
  await page.setViewportSize({width,height});const size=await page.locator('#shop').evaluate(e=>({w:e.clientWidth,scroll:e.scrollWidth,columns:getComputedStyle(e.querySelector('.shop-departments')!).gridTemplateColumns.split(' ').length}));expect(size.scroll).toBeLessThanOrEqual(size.w+1);expect(size.columns).toBe(width<=640?2:3);await page.screenshot({path:`docs/apercus/boutique-rayons/controle/${info.project.name}-${width}-accueil.png`});
 }
 expect(errors).toEqual([]);
});
test('Boutique : lots, total, double confirmation, achats répétés et sauvegarde',async({page},info)=>{
 const seed=rich();await boot(page,seed);await openMenuPage(page,'shop-open');const initial=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)!).tackle.config,key);
 await product(page,'corn');await page.locator('#shop-quantity').fill('3');await expect(page.locator('#shop-detail-total')).toContainText('45 portions · Total 24 écus');await page.screenshot({path:`docs/apercus/boutique-rayons/controle/${info.project.name}-fiche-mais.png`});await page.locator('#shop-detail-buy').click();
 await page.locator('#component-confirm').evaluate((b:HTMLButtonElement)=>{b.click();b.click();});
 await expect(page.locator('#component-detail')).not.toBeVisible();await expect(page.locator('[data-shop-product="corn"]')).toContainText('45 portions');
 await product(page,'corn');await page.locator('#shop-quantity').fill('2');await page.locator('#shop-detail-buy').click();await page.locator('#component-confirm').click();await page.reload();await expect(page.locator('body')).toHaveAttribute('data-ready','true');
 const s=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)!),key);expect(s.coins).toBe(460);expect(s.tackle.stock.corn).toBe(75);expect(s.tackle.config).toEqual(initial);expect(s.version).toBe(7);
});
test('Boutique : vrais filtres, retour de fiche, position, recherche générale et vide',async({page},info)=>{
 await boot(page,rich());await openMenuPage(page,'shop-open');await page.locator('[data-shop-department="bait"]').click();await page.locator('[data-shop-group="Appâts"]').click();await page.locator('#shop-compatible').check();
 const ids=await page.locator('[data-shop-product]').evaluateAll(es=>es.map(e=>(e as HTMLElement).dataset.shopProduct!)),s=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)!),key);expect(ids.every(id=>shopCompatible(SHOP_PRODUCTS.find(p=>p.id===id)!,s))).toBe(true);
 const card=page.locator('.shop-product').last();await card.scrollIntoViewIfNeeded();const scroll=await page.locator('#shop').evaluate(e=>e.scrollTop);await card.click();await page.locator('[data-close="component-detail"]').click();await expect(page.locator('#shop-compatible')).toBeChecked();await expect(page.locator('[data-shop-group="Appâts"]')).toHaveAttribute('aria-pressed','true');await expect.poll(()=>page.locator('#shop').evaluate(e=>e.scrollTop)).toBe(scroll);await expect(card).toBeFocused();
 await page.locator('#shop-subfamily').selectOption('mais');await expect(page.locator('.shop-product')).toHaveCount(1);await page.locator('[data-shop-product="corn"]').click();await page.locator('[data-close="component-detail"]').click();await expect(page.locator('#shop-subfamily')).toHaveValue('mais');
 await page.locator('#shop-query').fill('rochers');await expect(page.locator('[data-shop-product="rocks"] .shop-rayon')).toHaveText('Décorations d’aquarium');await page.locator('#shop-query').fill('zzintrouvable');await expect(page.locator('#shop-list')).toContainText('Aucun article');await page.screenshot({path:`docs/apercus/boutique-rayons/controle/${info.project.name}-vide.png`});await page.locator('[data-shop-reset]').click();await expect(page.locator('#shop-query')).toHaveValue('');
});
test('Boutique : incompatibilité, déblocage précis, argent et quantité invalide distincts',async({page})=>{
 await boot(page);await openMenuPage(page,'shop-open');await product(page,'minnow');await expect(page.locator('#component-detail')).toContainText('Incompatible');await expect(page.locator('#component-detail')).toContainText('Première prise + initiation aux leurres');await expect(page.locator('#shop-detail-buy')).toHaveCount(0);await page.locator('[data-close="component-detail"]').click();
 await product(page,'corn');await expect(page.locator('#component-detail')).toContainText('Compatible avec votre canne');await expect(page.locator('#shop-detail-error')).toContainText('Argent insuffisant');await expect(page.locator('#shop-detail-buy')).toBeDisabled();await page.locator('#shop-quantity').fill('0');await expect(page.locator('#shop-detail-total')).toContainText('1 et 20');await expect(page.locator('#shop-detail-buy')).toBeDisabled();await page.locator('#shop-quantity').fill('1.5');await expect(page.locator('#shop-detail-buy')).toBeDisabled();
});
test('Boutique : achat et équipement durables distincts, annulation et droit acquis',async({page})=>{
 await boot(page,rich());await openMenuPage(page,'shop-open');await product(page,'pole-elastic');await expect(page.locator('#item-sheet')).toContainText('Face à Canne au coup 6 m');await page.locator('#shop-detail-buy').click();await page.locator('[data-close="purchase-confirm"]').click();expect(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)!).coins,key)).toBe(500);await page.locator('#shop-detail-buy').click();await page.locator('#purchase-yes').click();expect(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)!).equipped,key)).toBe('pole-starter');
 await product(page,'pole-elastic');await expect(page.locator('#shop-detail-buy')).toHaveCount(0);await page.locator('#shop-detail-equip').click();await expect(page.locator('#item-sheet .state-pill')).toHaveText('Équipé');await page.locator('[data-close="item-sheet"]').click();await page.reload();await expect(page.locator('body')).toHaveAttribute('data-ready','true');const s=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)!),key);expect(s.equipped).toBe('pole-elastic');expect(s.coins).toBe(435);expect(s.inventory.filter((id:string)=>id==='pole-elastic')).toHaveLength(1);
});
test('Boutique : décor depuis aquarium et retour conserve individus et choix',async({page},info)=>{
 const s=rich();recordCatch(s,{id:'shop-memory',speciesId:'roach',length:20,date:'2026-10-04T12:00:00Z',method:'pole'});s.favorites=['shop-memory'];await boot(page,s);await openMenuPage(page,'aquarium-open');await expect(page.locator('#aquarium-canvas')).toHaveAttribute('data-loaded','true');await page.locator('#aq-decor-open').click();await page.locator('#aq-shop').click();await expect(page.locator('.shop-product')).toHaveCount(2);await expect(page.locator('[data-shop-product="balanced"]')).toHaveCount(0);await page.locator('[data-shop-product="plants"]').click();await page.locator('#shop-detail-buy').click();await page.locator('#purchase-yes').click();await page.screenshot({path:`docs/apercus/boutique-rayons/controle/${info.project.name}-decor.png`});await page.locator('[data-close="shop"]').click();await expect(page.locator('#aquarium-decor')).toBeVisible();await expect(page.locator('#aq-plants')).toBeEnabled();await page.locator('#aq-plants').check();const after=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)!),key);expect(after.favorites).toEqual(s.favorites);expect(after.journal).toEqual(s.journal);expect(after.aquarium.plants).toBe(true);
});
test('Boutique : Mode test public ∞ et achats conservent le profil normal',async({page})=>{
 await boot(page);const original=await page.evaluate(k=>localStorage.getItem(k),key);await openMenuPage(page,'help-open');await page.locator('#test-open').click();await page.locator('#test-toggle').click();await expect(page.locator('#test-badge')).toBeVisible();await openMenuPage(page,'shop-open');await expect(page.locator('#shop-balance')).toContainText('∞');await product(page,'precision');await page.locator('#shop-detail-buy').click();await page.locator('#purchase-yes').click();await product(page,'corn');await page.locator('#shop-quantity').fill('20');await page.locator('#shop-detail-buy').click();await page.locator('#component-confirm').click();const testSave=await page.evaluate(()=>JSON.parse(localStorage.getItem('au-fil-de-leau.test.save.v1')!));expect(testSave.tackle.stock.corn).toBe(300);expect(testSave.development.theoreticalCost).toBe(320);expect(await page.evaluate(k=>localStorage.getItem(k),key)).toBe(original);
});
