import {buyShopProduct,equipShopRod,openShopProduct} from './helpers';
import {ensureLegacyProfile} from './helpers';
import {test,expect} from '@playwright/test';
import {legacySave as emptySave} from '../support/legacy';
import {recordCatch} from '../../src/game/save';
import {openMenuPage,castByGesture,chooseMethod} from './helpers';
test('FishDex principal, fiches, variantes, filtres combinés et retour au catalogue',async({page},info)=>{
 const seed=emptySave();recordCatch(seed,{id:'first',speciesId:'roach',length:20,date:'2026-09-30T12:00:00Z'});recordCatch(seed,{id:'gold',speciesId:'roach',length:30,date:'2026-10-01T12:00:00Z',coloration:'golden',method:'bottom'});recordCatch(seed,{id:'other',speciesId:'perch',length:25,date:'2026-10-01T12:00:00Z'});seed.favorites=['gold'];
 await page.addInitScript(s=>{if(!localStorage.getItem('au-fil-de-leau.save.v1'))localStorage.setItem('au-fil-de-leau.save.v1',JSON.stringify(s));},seed);
 await ensureLegacyProfile(page); await page.goto('/');await expect(page.locator('body')).toHaveAttribute('data-ready','true');await page.locator('#menu-open').click();expect(await page.locator('.menu-links button').first().getAttribute('id')).toBe('dex-open');await page.locator('#dex-open').click();
 await page.locator('#dex-filters').evaluate((e:HTMLDetailsElement)=>e.open=true);await page.locator('#dex-state').selectOption('missing');await expect(page.locator('.dex-tile')).toHaveCount(64);await page.locator('#dex-filters').evaluate((e:HTMLDetailsElement)=>e.open=true);await page.locator('#dex-state').selectOption('discovered');await page.locator('#dex-search').fill('gardon');await page.locator('.dex-tile').click();
 await expect(page.locator('#species-sheet-title')).toContainText('Gardon');await expect(page.locator('#species-sheet')).toContainText('30 cm');await expect(page.locator('#species-sheet')).toContainText('Dorée');await page.screenshot({path:`test-results/regression/structure/final-${info.project.name}-species.png`});await page.locator('#species-journal').click();
 await expect(page.locator('.specimen-card')).toHaveCount(2);await page.locator('#collection .filter-panel summary').click();await page.locator('#journal-variant').selectOption('golden');await page.locator('#journal-method').selectOption('bottom');await expect(page.locator('.specimen-card')).toHaveCount(1);await expect(page.locator('#journal-results')).toContainText('3 filtre(s)');await page.locator('[data-specimen="gold"]').click();await expect(page.locator('#fish-preview')).toHaveAttribute('data-loaded','true');await page.locator('#release-fish').click();await expect(page.locator('#journal-variant')).toHaveValue('golden');
 await page.screenshot({path:`test-results/regression/structure/final-${info.project.name}-journal-filtered.png`});await page.locator('#journal-reset').click();await page.locator('#journal-view').selectOption('records');await expect(page.locator('.specimen-card')).toHaveCount(2);await page.locator('#journal-view').selectOption('favorites');await expect(page.locator('.specimen-card')).toHaveCount(1);await page.locator('[data-close="collection"]').click();await page.locator('[data-close="species-sheet"]').click();await expect(page.locator('#dex-search')).toHaveValue('gardon');await page.locator('#dex-search').fill('');await page.locator('#dex-filters').evaluate((e:HTMLDetailsElement)=>e.open=true);await page.locator('#dex-state').selectOption('observation');await expect(page.locator('.dex-tile')).toHaveCount(14);await page.locator('.dex-tile').first().click();await expect(page.locator('#species-sheet')).toContainText('12 secondes');await expect(page.locator('#species-journal')).toHaveCount(0);
});
test('Matériel, confirmation, progression et accès aux milieux sans déplacement silencieux',async({page},info)=>{
 const seed=emptySave();seed.coins=300;
 await page.addInitScript(s=>{if(!localStorage.getItem('au-fil-de-leau.save.v1'))localStorage.setItem('au-fil-de-leau.save.v1',JSON.stringify(s));},seed);await ensureLegacyProfile(page); await page.goto('/');await expect(page.locator('body')).toHaveAttribute('data-ready','true');await openMenuPage(page,'shop-open');await openShopProduct(page,'precision');await expect(page.locator('#item-sheet')).toContainText('Niveau 2');await expect(page.locator('#shop-detail-buy')).toHaveCount(0);await page.locator('[data-close="item-sheet"]').click();await buyShopProduct(page,'balanced');await page.locator('[data-close="purchase-confirm"]').click();await page.locator('[data-close="item-sheet"]').click();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('au-fil-de-leau.save.v1')!).coins)).toBe(300);await buyShopProduct(page,'balanced');await page.locator('#purchase-yes').click();await equipShopRod(page,'balanced');await page.locator('[data-close="shop"]').click();
 await openMenuPage(page,'equipment-open');await chooseMethod(page,'bottom');await expect(page.locator('[data-work-rig]').first()).toContainText('Fond');await page.locator('[data-close="preparation"]').click();await openMenuPage(page,'locations-open');await page.locator('[data-location="running-river"]').click();await expect(page.locator('#location-select')).toHaveCount(1);await page.locator('[data-close="location-sheet"]').click();await page.screenshot({path:`test-results/regression/structure/final-${info.project.name}-locations.png`});await page.locator('[data-close="locations"]').click();await openMenuPage(page,'progress-open');await page.locator('[data-progress-tab="badges"]').click();await page.locator('[data-objective="first"]').click();await page.locator('#badge-target').click();await expect(page.locator('#encyclopedia')).toBeVisible();await page.reload();await expect(page.locator('body')).toHaveAttribute('data-ready','true');const s=await page.evaluate(()=>JSON.parse(localStorage.getItem('au-fil-de-leau.save.v1')!));expect(s.equipped).toBe('balanced');expect(s.coins).toBe(230);expect(s.preparation.method).toBe('bottom');
});
test('Appui seul, deux commandes indépendantes et interruption sans moulinage bloqué',async({page,context},info)=>{
 await ensureLegacyProfile(page); await page.goto('/');await expect(page.locator('body')).toHaveAttribute('data-ready','true');await openMenuPage(page,'help-open');await expect(page.locator('#reel-mode')).toHaveCount(0);await page.locator('[data-close="help"]').click();await page.locator('[data-close="menu"]').click();await page.evaluate(()=>(window as any).__fishingQA.pauseSimulation());await castByGesture(page);await page.evaluate(()=>(window as any).__fishingQA.advance(45));await page.locator('#strike').click();const b=(await page.locator('#reel-control').boundingBox())!,cx=b.x+b.width/2,cy=b.y+b.height/2;
 if(info.project.name==='mobile'){const session=await context.newCDPSession(page),r=(await page.locator('#rod-control').boundingBox())!,rod={id:10,x:r.x+r.width/2,y:r.y+r.height/2};await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[rod,{id:20,x:cx+28,y:cy}]});expect(await page.evaluate(()=>(window as any).__fishingQA.snapshot().reeling)).toBe(true);for(let i=1;i<=16;i++)await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...rod,x:rod.x+15,y:rod.y-12},{id:20,x:cx+28*Math.cos(i*Math.PI/8),y:cy+28*Math.sin(i*Math.PI/8)}]});expect(await page.evaluate(()=>(window as any).__fishingQA.snapshot().reeling)).toBe(true);await session.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});}
 else {await page.mouse.move(cx+28,cy);await page.mouse.down();expect(await page.evaluate(()=>(window as any).__fishingQA.snapshot().reeling)).toBe(true);for(let i=1;i<=16;i++)await page.mouse.move(cx+28*Math.cos(i*Math.PI/8),cy+28*Math.sin(i*Math.PI/8));expect(await page.evaluate(()=>(window as any).__fishingQA.snapshot().reeling)).toBe(true);await page.mouse.up();}
 expect(await page.evaluate(()=>(window as any).__fishingQA.snapshot().reeling)).toBe(false);await page.locator('#menu-open').click();await expect(page.locator('#menu')).toBeVisible();const snap=await page.evaluate(()=>(window as any).__fishingQA.snapshot());expect(snap.paused).toBe(true);
});
