import {test,expect} from '@playwright/test';
import {openMenuPage} from './helpers';
import {TECHNIQUES} from '../../src/game/techniques';
import {mkdir,writeFile} from 'node:fs/promises';
const qa=(page:any)=>page.evaluate(()=>(window as any).__fishingQA.snapshot());
async function tools(page:any){await openMenuPage(page,'help-open');await page.locator('#test-open').click();}
async function closeTools(page:any){for(const id of ['test-tools','help','menu'])if(await page.locator('#'+id).isVisible())await page.locator(`[data-close="${id}"]`).click();}

test('Scénarios : poste et milieu cohérents après reload, nouveau kit sans ancien courant forcé',async({page})=>{
 await page.goto('/');await expect(page.locator('body')).toHaveAttribute('data-ready','true');await tools(page);await page.locator('#test-toggle').click();await expect(page.locator('body')).toHaveAttribute('data-ready','true');await tools(page);
 await page.locator('#test-post').selectOption('river');const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('au-fil-de-leau.test.save.v1')!));expect(before.preparation.location).toBe('running-river');expect(before.preparation.post).toBe('river');await page.reload();await expect(page.locator('body')).toHaveAttribute('data-ready','true');expect((await qa(page)).post).toBe('river');
 await tools(page);await page.locator('#test-current').fill('0.8');await page.locator('#test-environment').click();await page.locator('#test-technique').selectOption('traine');await page.locator('#test-kit').click();await page.locator('#test-tools details summary').click();await expect(page.locator('#test-diagnostics')).toContainText('"current": 0');await expect(page.locator('#test-diagnostics')).toContainText('"wind": 0');
});
test('Catalogue V2 : les 22 chaînes UI/combat/réception/photo/reload dans le profil isolé',async({page},info)=>{
 test.setTimeout(180000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{localStorage.setItem('au-fil-de-leau.gestures.v3','3');});await page.goto('/');await expect(page.locator('body')).toHaveAttribute('data-ready','true');const original=await page.evaluate(()=>localStorage.getItem('au-fil-de-leau.save.v1'));await tools(page);await page.locator('#test-toggle').click();await expect(page.locator('body')).toHaveAttribute('data-ready','true');await page.evaluate(()=>(window as any).__fishingQA.pauseSimulation());
 const rows=[];await mkdir('docs/apercus/v2',{recursive:true});
 for(const t of TECHNIQUES){await tools(page);await page.locator('#test-technique').selectOption(t.id);await page.locator('#test-kit').click();expect((await qa(page)).technique).toBe(t.id);await page.locator('#test-fight').click();await page.evaluate(()=>(window as any).__fishingQA.advance(.02));await expect(page.locator('body')).toHaveAttribute('data-phase','fighting');expect((await qa(page)).hasReel).toBe(t.reel);await page.evaluate(()=>(window as any).__fishingQA.advance(240,'smart'));const phase=(await qa(page)).phase;expect(phase,t.id).toBe('landing');if(t.sections){const b=(await page.locator('#tech-hold').boundingBox())!;await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.evaluate(()=>(window as any).__fishingQA.advance(15));await page.mouse.up();}else await page.evaluate(()=>(window as any).__fishingQA.advance(1.2));await expect(page.locator('#tech-land')).toBeEnabled();if(['gambe','grande_canne','mouche'].includes(t.id))await page.screenshot({path:`docs/apercus/v2/${info.project.name}-${t.id}-landing.png`});await page.locator('#tech-land').click();await page.evaluate(()=>(window as any).__fishingQA.advance(.05));await expect(page.locator('#caught')).toBeVisible();await expect(page.locator('#fish-preview')).toHaveAttribute('data-loaded','true');await expect(page.locator('#photo-state')).toContainText('Photo conservée');const s=await page.evaluate(()=>JSON.parse(localStorage.getItem('au-fil-de-leau.test.save.v1')!));expect(s.journal.at(-1).technique).toBe(t.id);expect(s.journal.at(-1).recipe).toBe(t.defaultRecipe);expect(s.total).toBe(rows.length+1);rows.push({technique:t.id,post:s.journal.at(-1).post,capture:s.journal.at(-1).id,photo:true});await page.locator('#release-fish').click();}
 await page.reload();await expect(page.locator('body')).toHaveAttribute('data-ready','true');expect((await qa(page)).total).toBe(22);expect(await page.evaluate(()=>localStorage.getItem('au-fil-de-leau.save.v1'))).toBe(original);expect(errors).toEqual([]);await writeFile(`docs/apercus/v2/${info.project.name}-22-chains.json`,JSON.stringify({viewport:page.viewportSize(),forcedEncounter:true,naturalEncountersVerifiedBy:'tests/techniques.test.ts',rows},null,2));
});
test('Ateliers V2 et milieux : variantes, soie, feeder, courant, bateau et interruptions',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.locator('body')).toHaveAttribute('data-ready','true');await tools(page);await page.locator('#test-toggle').click();await expect(page.locator('body')).toHaveAttribute('data-ready','true');await page.evaluate(()=>(window as any).__fishingQA.pauseSimulation());await tools(page);await page.locator('#test-technique').selectOption('mouche');await page.locator('#test-kit').click();await closeTools(page);await page.locator('#prepare-open').click();await page.locator('[data-work-rig]').first().click();await expect(page.locator('.rig-fly')).toBeVisible();await expect(page.locator('.rig-float')).toHaveCount(0);await page.locator('#rig-recipe').selectOption('streamer');await expect(page.locator('#rig-recipe')).toHaveValue('streamer');await page.screenshot({path:`docs/apercus/v2/${info.project.name}-fly-rig.png`});await page.locator('#rig-done').click();await page.locator('[data-close="preparation"]').click();
 await tools(page);await page.locator('#test-technique').selectOption('bolognaise');await page.locator('#test-kit').click();await page.locator('#test-current').fill('0.8');await page.locator('#test-wind').fill('0.3');await page.locator('#test-environment').click();await closeTools(page);await page.screenshot({path:`docs/apercus/v2/${info.project.name}-river.png`});await tools(page);await page.locator('#test-technique').selectOption('traine');await page.locator('#test-kit').click();await closeTools(page);
 const {width:w,height:h}=page.viewportSize()!;await page.mouse.move(w*.5,h*.8);await page.mouse.down();await page.mouse.move(w*.5,h*.46,{steps:8});await page.mouse.up();await expect(page.locator('body')).toHaveAttribute('data-phase','casting');await page.evaluate(()=>(window as any).__fishingQA.advance(2));expect((await qa(page)).boat.z).toBe(0);await page.locator('#tech-settings summary').click();await page.locator('#tech-speed').selectOption('1.2');await page.evaluate(()=>(window as any).__fishingQA.advance(3));expect((await qa(page)).boat.z).toBeGreaterThan(3);await page.screenshot({path:`docs/apercus/v2/${info.project.name}-trolling.png`});await page.locator('#cancel-cast').click();expect((await qa(page)).phase).toBe('idle');expect(errors).toEqual([]);
});
