import {manageFight} from './support/combat.ts';
import test from 'node:test';import assert from 'node:assert/strict';
import {stepCombat,rodGeometry,type CombatState,type CombatInput} from '../src/game/combat.ts';import {ActionGesture} from '../src/game/action-gesture.ts';import {FishingGame} from '../src/game/fishing.ts';import {createTestSave,prepareTestKit} from '../src/game/development.ts';import {switchTechnique} from '../src/game/progression.ts';import {emptySave,parseSave} from '../src/game/save.ts';
const input:CombatInput={yaw:0,lift:.4,bearing:.35,force:1.3,power:1,reelSpeed:0,motion:'burst',drag:.5};
const state:CombatState={distance:10,lineLength:11,tension:.6,fatigue:0,position:{x:1,y:-.6,z:9},velocity:{x:0,z:0}};
function run(s:CombatState,i:CombatInput,seconds:number,hz=60){let next=stepCombat(s,i,1/hz);for(let n=1;n<seconds*hz;n++)next=stepCombat(next,i,1/hz);return next;}
test('Géométrie : charge à l’arrêt, zéro traction avec mou, aucun gain gratuit par un changement de pose',()=>{const taut=stepCombat({...state,lineLength:8},{...input,motion:'rest'},1/60),slack=stepCombat({...state,lineLength:30},{...input,motion:'rest'},1/60);assert.ok(taut.tension>0);assert.equal(slack.tension,0);assert.equal(slack.fatigue,0);assert.deepEqual(slack.position,state.position);const high=stepCombat({...state,lineLength:30},{...input,lift:1,motion:'rest'},1/60);assert.deepEqual(high.position,state.position);});
test('Moulinage mécanique : un fort départ peut faire sortir du fil malgré l’appui, sans pénalité arbitraire',()=>{const a=run({...state,lineLength:10},{...input,reelSpeed:1.6,force:2.2},3);assert.ok(a.dragSpeed>0);assert.ok(a.tension>.3);const stopped=run({...state,lineLength:10},{...input,reelSpeed:0,force:2.2},3);assert.ok(a.tension<1.1);assert.ok(stopped.tension<1.1);assert.ok(a.lineLength>10);});
test('Retour et récupération du mou ; traction latérale issue de la position du scion',()=>{const a=run({...state,lineLength:12},{...input,motion:'return'},3),b=run({...state,lineLength:12},{...input,motion:'return',reelSpeed:1.6},3);assert.ok(a.slack>b.slack);const left=stepCombat({...state,lineLength:8},{...input,yaw:-.8},1/60),right=stepCombat({...state,lineLength:8},{...input,yaw:.8},1/60);assert.notEqual(left.velocity.x,right.velocity.x);assert.notDeepEqual(left.rod.tip,right.rod.tip);});
test('Simulation physique reproductible à 30 et 60 Hz',()=>{const a=run(state,{...input,reelSpeed:1},10,30),b=run(state,{...input,reelSpeed:1},10,60);for(const key of ['distance','lineLength','fatigue','tension'] as const)assert.ok(Math.abs(a[key]-b[key])<1e-8,key);});
test('Grande canne : recul puis déboîtement, scion continu et ligne fixe, réemboîtement possible',()=>{const s=createTestSave();prepareTestKit(s,'grande_canne');const g=new FishingGame();g.testMode=true;g.tackle=s.tackle;g.equipment=s.equipped;g.method='pole';g.testTarget={x:0,z:7};g.testEncounter('roach',15,127,true);const line=g.lineLength;g.rodLift=.18;for(let n=0;n<10;n++)g.movePole(.2);assert.ok(g.canDetach);const before=rodGeometry(g.rodYaw,g.rodLift,g.rodLength,g.poleRetreat).tip;assert.ok(g.detachPole());const after=rodGeometry(g.rodYaw,g.rodLift,g.rodLength,g.poleRetreat).tip;for(const k of ['x','y','z'] as const)assert.ok(Math.abs(before[k]-after[k])<1e-8);assert.equal(g.lineLength,line);assert.ok(g.detachPole(true));assert.equal(g.lineLength,line);const fixed=new FishingGame();assert.equal(fixed.detachPole(),false);});
test('Axes de manipulation verrouillés, pas de déboîtement au simple maintien',()=>{const g=new ActionGesture(0,0,0,'pole');assert.equal(g.move(0,15,100).detach,false);assert.equal(g.move(80,18,200).detach,false);const side=new ActionGesture(0,0,0,'pole');assert.equal(side.move(30,1,100).detach,true);assert.equal(side.move(60,50,200).detach,false);assert.equal(side.axis,'horizontal');});
test('Réception : ni attente ni bouton ne donnent une capture ; position et relevage nécessaires',()=>{const g=new FishingGame();g.testMode=true;g.testTarget={x:0,z:2.2};g.testEncounter('roach',15,127,true);assert.equal(g.beginLanding(),false);for(let n=0;n<18000&&!g.canReceive&&g.phase==='fighting';n++)manageFight(g,false,false);assert.ok(g.fatigue>=g.receptionFatigue);assert.ok(g.beginLanding());assert.equal(g.receive(),false);g.netPosition={x:2.8,z:.15};assert.equal(g.liftNet(.4),false);g.placeNet(g.fishPosition.x,g.fishPosition.z);g.netHeading=0;g.testCombatScenario('quiet');for(let n=0;n<6000&&!g.netReady&&g.phase==='landing';n++){manageFight(g,false,false);g.placeNet(g.fishPosition.x,g.fishPosition.z);}assert.ok(g.netReady);assert.ok(g.liftNet(.4));assert.equal(g.phase,'caught');assert.equal(g.receive(),false);});
test('Préférences accessibles migrées sans altérer le carnet v7 ni l’ancienne option de comparaison',()=>{const s=emptySave();delete s.settings.controls;s.settings.combatMode='assisted';const loaded=parseSave(JSON.stringify(s));assert.equal(loaded.total,0);assert.equal(loaded.settings.combatMode,'assisted');assert.deepEqual(loaded.settings.controls,{side:'left',singleFinger:false,tension:false,hints:true});});

test('Le courant ajoute une dérive mesurable sans multiplier la force intrinsèque du même poisson',()=>{const a=run(state,{...input,current:0},3),b=run(state,{...input,current:.45},3);const calm=stepCombat(state,{...input,current:0},1/120),river=stepCombat(state,{...input,current:.45},1/120);assert.equal(calm.relativeForce,river.relativeForce);assert.notDeepEqual(a.position,b.position);});
