import {manageFight} from './support/combat.ts';
import test from 'node:test';
import assert from 'node:assert/strict';
import {TECHNIQUES,RECIPES,techniqueById,type TechniqueId} from '../src/game/techniques.ts';
import {createTestSave} from '../src/game/development.ts';
import {switchTechnique,refreshRights,techniqueAccess,restoreFreeKit} from '../src/game/progression.ts';
import {FishingGame} from '../src/game/fishing.ts';
import {ITEMS} from '../src/game/economy.ts';
import {emptySave,recordCatch,parseSave} from '../src/game/save.ts';
import {techniqueConfig,validateRig,reserveRig,resolveRig,component,parseTackle} from '../src/game/rig.ts';
import {initialPresentation,stepPresentation,recipeMechanics} from '../src/game/presentation.ts';
import {stepCombat} from '../src/game/combat.ts';

function prepare(id:TechniqueId,recipe?:string){const save=createTestSave();assert.equal(switchTechnique(save,id,recipe),'');const t=techniqueById(id),game=new FishingGame(()=>.01);game.tackle=save.tackle;game.testMode=true;game.method=t.base;game.equipment=save.equipped;game.equipmentPower=ITEMS.find(i=>i.id===save.equipped)!.power;game.rights=save.progression;const post=t.context.includes('pond')?'jetty':t.context.includes('river')?'river':t.context.includes('deep')?'deep':'boat';assert.equal(game.setPost(post),true);save.preparation.post=post;save.preparation.location=post==='river'?'running-river':post==='deep'?'deep-lake':post==='boat'?'light-boat':'willow-pond';if(t.engine==='feeder')game.fillFeeder();if(t.engine==='fly'){game.prepareFly();game.prepareFly();}if(t.engine==='troll')game.setBoat(1,0);return {save,game,t};}
function natural(id:TechniqueId,recipe?:string){const state=prepare(id,recipe),{game:g,save,t}=state;assert.equal(g.cast({x:0,z:3.2}),true,g.failure);assert.equal(g.fish,null);
 for(let n=0;n<7200&&['casting','waiting'].includes(g.phase);n++){if(g.phase==='waiting'){if(t.engine==='retrieve'||t.engine==='fly'&&save.tackle.config.recipe==='streamer'||t.engine==='bottom'||t.engine==='feeder')g.reel(.8/60);if(t.engine==='vertical'||t.engine==='clonk')g.orient(0,.5+Math.sin(n/20)*.2);if(t.engine==='drift')g.holdRestraint(true);if(t.engine==='clonk')g.clonk();}g.update(1/60);}
 assert.ok(['bite','fighting'].includes(g.phase),`${id}/${recipe}: aucune rencontre ${g.failure}`);const fish=g.fish!.id,size=g.fishLength;if(g.phase==='bite')g.strike();
 for(let n=0;n<18000&&g.phase==='fighting';n++)manageFight(g,false);
 assert.equal(g.phase,'landing',id+'/'+recipe+': '+g.failure);assert.equal(g.result,null);assert.equal(save.total,0);assert.ok(g.canReceive);
 for(let n=0;n<6000&&['fighting','landing'].includes(g.phase);n++)manageFight(g);assert.equal(g.phase,'caught',g.failure);assert.equal(g.result!.speciesId,fish);assert.equal(g.result!.length,size);assert.equal(g.result!.technique,id);recordCatch(save,g.result!);const coins=save.coins;recordCatch(save,g.result!);assert.equal(save.total,1);assert.equal(save.coins,coins);assert.equal(save.progression.techniqueMastery![id],1);assert.deepEqual(parseSave(JSON.stringify(save)),save);return state;
}
for(const t of TECHNIQUES)test(`V2 ${t.id}: rencontre naturelle, gestes, combat, réception et carnet uniques`,()=>{natural(t.id);});
test('55 recettes raccordées : montage, stock, moteur, réception et sauvegarde',()=>{assert.equal(RECIPES.length,55);for(const r of RECIPES){const id=r.techniques[0] as TechniqueId;natural(id,r.id);}});
test('Feeder et soie exigent une vraie préparation ; interruption avant impact ne consomme rien',()=>{for(const id of ['feeder','mouche'] as const){const {game:g,save}=prepare(id);g.feederFilled=false;g.flyEnergy=0;assert.equal(g.cast({x:0,z:3.2}),false);assert.equal(save.tackle.active,null);}const {game:g,save}=prepare('feeder');save.tackle.config.components.groundbait='v2:groundbait';save.tackle.stock['v2:groundbait']=15;assert.equal(g.cast({x:0,z:3.2}),true);g.reset();assert.equal(save.tackle.stock['v2:groundbait'],15);g.fillFeeder();g.cast({x:0,z:3.2});for(let n=0;n<70;n++)g.update(1/60);g.reset();assert.equal(save.tackle.stock['v2:groundbait'],14);g.reset();assert.equal(save.tackle.stock['v2:groundbait'],14);});
test('Grande canne : le maintien ne déboîte pas ; recul et geste latéral sont nécessaires',()=>{const {game:g}=prepare('grande_canne');assert.equal(g.testEncounter('roach',10,127,true),'');g.holdSections(true);g.update(.05);assert.equal(g.rodSections,12);assert.equal(g.receive(),false);g.orient(0,.18);g.update(.05);for(let n=0;n<10;n++)g.movePole(.2);assert.ok(g.detachPole());assert.ok(g.rodSections<12);assert.equal(g.hasReel,false);assert.equal(g.reelSpeed,0);});
test('Courant et retenue déplacent effectivement la ligne ; vitesse bateau anime seulement la traîne',()=>{const c=techniqueConfig('bolognaise'),a=initialPresentation(),b=initialPresentation();for(let n=0;n<600;n++){const i={dt:1/60,waterDepth:2,reelSpeed:0,lift:.5,current:.45,wind:.3,boatSpeed:0,boatTurn:0,clonk:false};stepPresentation(c,a,{...i,restrained:false});stepPresentation(c,b,{...i,restrained:true});}assert.ok(a.point.x>b.point.x*3);const troll=techniqueConfig('traine'),s=initialPresentation();stepPresentation(troll,s,{dt:.05,waterDepth:10,reelSpeed:0,lift:.5,current:0,wind:0,boatSpeed:0,boatTurn:0,clonk:false,restrained:false});assert.equal(s.activity,0);stepPresentation(troll,s,{dt:.05,waterDepth:10,reelSpeed:0,lift:.5,current:0,wind:0,boatSpeed:1,boatTurn:1,clonk:false,restrained:false});assert.ok(s.activity>0&&s.boat.z>0&&s.boat.x>0);});
test('Gambe : trois potences réelles, couches espacées et seule branche ferrée perdue',()=>{const {save}=prepare('gambe');save.tackle.config.components.fly='v2:fly';save.tackle.stock['v2:fly']=10;assert.deepEqual(reserveRig(save.tackle,'branches','deep-rod'),[]);const flies=save.tackle.active!.nodes.filter(n=>n.slot==='fly');assert.equal(flies.length,3);assert.deepEqual(flies.map(n=>n.offset),[0,.5,1]);save.tackle.active!.hookedBranch=1;assert.deepEqual(resolveRig(save.tackle,'branches','hook'),{'v2:fly':1});assert.equal(save.tackle.stock['v2:fly'],9);});
test('Propriétés : PVA retarde, pop-up surélève, drop-shot sépare le lest, frein modifie la sortie',()=>{const c=techniqueConfig('carpe','pva_solide'),s=initialPresentation();s.pvaRemaining=8;const input={dt:.05,waterDepth:3,reelSpeed:1,lift:.5,current:0,wind:0,boatSpeed:0,boatTurn:0,clonk:false,restrained:false};stepPresentation(c,s,input);assert.equal(s.activity,0);assert.equal(s.pvaRemaining,7.95);assert.ok(recipeMechanics(techniqueConfig('carpe','chod')).terminalHeight>0);const {save}=prepare('leurre','drop_shot');Object.assign(save.tackle.config.components,{weight:'v2:weight',leader:'v2:leader',lure:'v2:lure'});Object.assign(save.tackle.stock,{'v2:weight':5,'v2:leader':10,'v2:lure':5});assert.deepEqual(reserveRig(save.tackle,'drop','starter'),[]);assert.deepEqual(resolveRig(save.tackle,'drop','weight_branch'),{'v2:weight':1,'v2:leader':.2});const state={distance:8,lineLength:7.5,tension:.5,fatigue:0},i={yaw:0,lift:.6,bearing:0,force:1,power:1,reelSpeed:0,motion:'burst' as const};assert.ok(stepCombat(state,{...i,drag:.1},.05).dragSpeed>stepCombat(state,{...i,drag:.9},.05).dragSpeed);});
test('Migration v5, droits permanents, composants réutilisables et rejets de données incohérentes',()=>{const original=emptySave();original.version=5 as never;original.coins=123;const migrated=parseSave(JSON.stringify(original));assert.equal(migrated.version,7);assert.equal(migrated.coins,123);assert.equal(migrated.total,0);migrated.xp=100000;refreshRights(migrated);for(const t of TECHNIQUES)assert.equal(techniqueAccess(migrated,t.id),true,t.id);migrated.xp=0;assert.equal(techniqueAccess(parseSave(JSON.stringify(migrated)),'gambe'),true);const {save}=prepare('nymphe_fil','nymphe');assert.deepEqual(validateRig(save.tackle),[]);assert.deepEqual(parseTackle(save.tackle).config,save.tackle.config);save.tackle.config.branchCount=1.5;assert.throws(()=>parseTackle(save.tackle));const {save:carp}=prepare('carpe');carp.tackle.config.components.bait='bait:mais_flottant';carp.tackle.stock['bait:mais_flottant']=15;assert.equal(component('bait:mais_flottant')!.slot,'bait');assert.equal(component('bait:mais_flottant')!.buoyancy,'float');reserveRig(carp.tackle,'maize','heavy-rod');carp.tackle.active!.used=true;resolveRig(carp.tackle,'maize','return');assert.equal(carp.tackle.stock['bait:mais_flottant'],15);const coins=carp.coins;assert.equal(restoreFreeKit(carp),'');assert.equal(carp.coins,coins);});
