import {test,expect} from '@playwright/test';
import {emptySave,recordCatch} from '../../src/game/save';
import {openMenuPage} from '../browser/helpers';
test.beforeEach(async({context})=>{const token=process.env.VERCEL_OIDC_TOKEN;if(token&&process.env.GAME_URL){const origin=new URL(process.env.GAME_URL).origin;await context.route(`${origin}/**`,route=>route.continue({headers:{...route.request().headers(),'x-vercel-trusted-oidc-idp-token':token}}));}});
test('Refonte publique : quatre sections, retours, sauvegarde et Mode test séparé',async({page},info)=>{
 const seed=emptySave();recordCatch(seed,{id:'public-review',speciesId:'roach',length:20,date:'2026-10-04T12:00:00Z',method:'pole'});seed.favorites=['public-review'];const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(s=>{localStorage.setItem('au-fil-de-leau.gestures.v3','3');if(!localStorage.getItem('au-fil-de-leau.save.v1'))localStorage.setItem('au-fil-de-leau.save.v1',JSON.stringify(s));},seed);await page.goto('/');await expect(page.locator('body')).toHaveAttribute('data-ready','true');expect(await page.evaluate(()=>'__fishingQA' in window)).toBe(false);
 await openMenuPage(page,'dex-open');await page.locator('#dex-search').fill('gardon');await page.locator('.dex-tile').click();await page.locator('#species-prepare').click();await expect(page.locator('#encounter-advice')).toBeVisible();await page.locator('[data-close="preparation"]').click();await page.locator('[data-close="species-sheet"]').click();await expect(page.locator('#dex-search')).toHaveValue('gardon');await page.locator('[data-close="encyclopedia"]').click();
 await openMenuPage(page,'progress-open');await page.locator('[data-progress-tab="techniques"]').click();await expect(page.locator('[data-progress-technique]')).toHaveCount(22);await page.locator('[data-close="progression"]').click();await openMenuPage(page,'locations-open');await page.locator('[data-location="willow-pond"]').click();await page.locator('[data-preview-post="jetty"]').click();await expect(page.locator('#map [data-post]')).toHaveCount(6);for(const id of ['map','location-sheet','locations'])await page.locator(`[data-close="${id}"]`).click();
 await openMenuPage(page,'collection-open');await expect(page.locator('[data-specimen]')).toHaveCount(1);await page.locator('#journal-query').fill('zzintrouvable');await expect(page.locator('#journal-list')).toContainText('Aucun souvenir');await page.locator('#journal-reset').click();await page.locator('#journal-save-link').click();await expect(page.locator('#export-save')).toBeVisible();await page.locator('[data-close="settings"]').click();await page.locator('[data-close="collection"]').click();await openMenuPage(page,'aquarium-open');await expect(page.locator('#aquarium-canvas')).toHaveAttribute('data-loaded','true');await page.locator('#aq-fish-open').click();await expect(page.locator('[data-aq-view]')).toHaveCount(1);await page.locator('[data-close="aquarium-fish"]').click();await page.locator('[data-close="aquarium"]').click();
 const normal=await page.evaluate(()=>localStorage.getItem('au-fil-de-leau.save.v1'));await openMenuPage(page,'help-open');await page.locator('#test-open').click();await page.locator('#test-toggle').click();await expect(page.locator('#test-badge')).toBeVisible();await openMenuPage(page,'help-open');await page.locator('#test-open').click();await expect(page.locator('#test-profile-state')).toContainText('∞');expect(await page.evaluate(()=>localStorage.getItem('au-fil-de-leau.save.v1'))).toBe(normal);await page.locator('#test-toggle').click();await expect(page.locator('#test-badge')).toBeHidden();await page.locator('#menu-open').click();await page.screenshot({path:`test-results/ui-public-${info.project.name}.png`});expect(errors).toEqual([]);
});
