import { COMPONENTS } from '../game/rig';
import { SPECIES } from '../game/catalog';
import { POSTS } from '../game/posts';
import { refillTestStock, wallet, type ProfileStorage } from '../game/development';
import type { ScreenHooks } from './structure';
const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
export function installDevelopment(h:ScreenHooks,profiles:ProfileStorage) {
 if(!profiles.enabled)return;
 el('help').insertAdjacentHTML('beforeend',`<div class="setting-row"><span>Profil de développement</span><button id="test-open">Mode test</button></div>`);
 el('app').insertAdjacentHTML('beforeend',`<span id="test-badge" class="test-badge" hidden>TEST</span><dialog id="test-tools" class="modal"><div class="modal-header"><h2>Mode test</h2><button class="close" data-close="test-tools">Retour</button></div><p class="intro" id="test-profile-state"></p><button id="test-toggle" class="action"></button><section id="test-scenarios" hidden><p class="warning-line">Carnet, achats, photos et aquarium séparés de la partie normale. Les scénarios forcés contournent habitat, appât et attente ; ils ne mesurent pas les distributions naturelles.</p><div class="filters"><label>Poste<select id="test-post">${POSTS.filter(p=>p.implemented).map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}</select></label><label>Espèce<select id="test-species">${SPECIES.map(s=>`<option value="${s.id}">${s.name}</option>`).join('')}</select></label><label>Taille (cm)<input id="test-length" type="number" min="1" max="220" value="15"></label><label>Graine<input id="test-seed" type="number" min="0" max="4294967295" value="127"></label></div><div class="tools"><button id="test-ready">Touche rapide</button><button id="test-fight">Combat direct</button><button id="test-replay">Rejouer ce poisson</button></div><div class="tools"><button data-test-outcome="unhook">Décrocher</button><button data-test-outcome="leader">Casse bas de ligne</button><button data-test-outcome="main_line">Casse fil</button><button data-test-outcome="hook">Casse hameçon</button><button id="test-snag">Accrocher la ligne</button><button id="test-free">Tester le dégagement</button></div><button id="test-refill" class="secondary">Réapprovisionner mon sac</button><label class="setting-row">Stock illimité<input id="test-stock" type="checkbox"></label><button id="test-empty" class="secondary">Épuiser les composants payants non engagés</button><details><summary>Diagnostics</summary><pre id="test-diagnostics"></pre></details><div class="tools"><button id="test-reset">Réinitialiser le profil de test</button><button id="test-rules">Partie de test neuve en règles normales</button></div></section></dialog>`);
 const render=()=>{const s=h.save(),test=profiles.active==='test';el('test-profile-state').textContent=test?`Profil TEST · ${wallet(s)} écus · coût théorique ${s.development?.theoreticalCost??0} écus`:'Partie normale : le Mode test possède son propre carnet.';el('test-toggle').textContent=test?'Revenir à ma partie normale':'Ouvrir mon profil de test';el('test-scenarios').hidden=!test;el('test-badge').hidden=!test||h.game.phase==='fighting';if(test){el<HTMLInputElement>('test-stock').checked=!!s.development?.unlimitedStock;el('test-diagnostics').textContent=JSON.stringify({phase:h.game.phase,post:h.game.post,depth:h.game.presentationDepth,tension:h.game.tension,fatigue:h.game.fatigue,distance:h.game.fishDistance,elapsed:h.game.elapsed,failure:h.game.failure,components:s.tackle.config.components,losses:s.tackle.active?.losses,cost:s.development?.theoreticalCost},null,2);}};
 const idle=()=>{if(h.game.phase!=='idle'){h.toast('Ramenez la ligne ou terminez la prise avant cette action.');return false;}return true;};
 el('test-open').onclick=()=>{render();h.open('test-tools');};
 el('test-toggle').onclick=()=>{if(!idle())return;try{profiles.switchTo(profiles.active==='test'?'normal':'test',h.save());location.reload();}catch(e){h.toast(String(e));}};
 const scenario=(direct:boolean)=>{if(!idle())return;const s=SPECIES.find(s=>s.id===el<HTMLSelectElement>('test-species').value)!;const size=Number(el<HTMLInputElement>('test-length').value),seed=Number(el<HTMLInputElement>('test-seed').value);if(!Number.isFinite(size)||!Number.isInteger(seed)){h.toast('Taille ou graine invalide.');return;}const error=h.game.testEncounter(s.id,size,seed,direct);if(error){h.toast(error);return;}h.persist();h.close('test-tools');if(el<HTMLDialogElement>('help').open)h.close('help');if(el<HTMLDialogElement>('menu').open)h.close('menu');h.toast('Scénario TEST : habitat, appât et délai contournés. Combat, pertes et récompense unique conservés.');};
 el('test-ready').onclick=()=>scenario(false);el('test-fight').onclick=el('test-replay').onclick=()=>scenario(true);
 el('test-post').onchange=()=>{if(!idle())return;const id=el<HTMLSelectElement>('test-post').value as typeof h.game.post;if(h.game.setPost(id)){h.save().preparation.post=id;h.postChanged?.();h.persist();render();}};
 el('test-tools').querySelectorAll<HTMLElement>('[data-test-outcome]').forEach(b=>b.onclick=()=>{h.game.testFailure(b.dataset.testOutcome as 'leader'|'main_line'|'hook'|'unhook');h.persist();render();});
 el('test-snag').onclick=()=>{h.game.testSnag();render();};el('test-free').onclick=()=>{h.toast(h.game.tryFreeSnag()?'Dégagement réussi.':'Baissez la canne et changez son angle, puis réessayez.');render();};
 el('test-refill').onclick=()=>{if(!idle())return;refillTestStock(h.save());h.persist();h.refresh();render();};
 el('test-stock').onchange=()=>{if(!idle()){render();return;}const s=h.save();s.development!.unlimitedStock=el<HTMLInputElement>('test-stock').checked;s.tackle.unlimitedStock=s.development!.unlimitedStock;h.persist();render();};
 el('test-empty').onclick=()=>{if(!idle())return;for(const c of COMPONENTS.filter(c=>!c.free))h.save().tackle.stock[c.id]=0;h.persist();h.refresh();render();};
 for(const [id,kind] of [['test-reset','sandbox'],['test-rules','rules']] as const)el(id).onclick=()=>{if(!idle())return;try{profiles.reset(kind);location.reload();}catch(e){h.toast(String(e));}};
 window.setInterval(()=>{if(el<HTMLDialogElement>('test-tools').open||profiles.active==='test')render();},500);render();
}
