import {COMPONENTS,available} from '../game/rig';
import type {ScreenHooks} from './structure';
const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
export function installFieldTools(h:ScreenHooks){
 el('groundbait').insertAdjacentHTML('beforebegin','<button id="survey-open" class="compact field-tool">Sonder / amorcer</button>');
 el('app').insertAdjacentHTML('beforeend','<dialog id="field-tools" class="modal detail-modal"><div class="modal-header"><h2>Sonder et amorcer</h2><button class="close" data-close="field-tools">Retour</button></div><p class="intro">Touchez un point devant le poste. Le sondage révèle le fond ; aucune espèce n’est révélée.</p><svg id="field-map" viewBox="0 0 300 250" role="img" aria-label="Zone de sondage et amorçage"><rect width="300" height="250" fill="#12363d"/><path d="M0 245H300" stroke="#e6c48d" stroke-width="8"/><circle id="field-point" cx="150" cy="180" r="9" fill="#61d5c7"/></svg><div class="filters"><label>Décalage (m)<input id="field-x" type="number" min="-10" max="10" step="0.2" value="0"></label><label>Distance (m)<input id="field-z" type="number" min="0.2" max="22" step="0.2" value="3.2"></label></div><p id="field-result" class="intro" aria-live="polite"></p><button id="field-survey" class="action">Sonder ce point</button><label>Amorce du sac<select id="field-bait"></select></label><label>Portions<select id="field-portions"><option value="1">1 portion</option><option value="2">2 portions</option><option value="3">3 portions</option></select></label><button id="field-baiting" class="secondary">Amorcer cette zone</button></dialog>');
 const point=()=>({x:Number(el<HTMLInputElement>('field-x').value),z:Number(el<HTMLInputElement>('field-z').value)});
 const marker=()=>{const p=point();el('field-point').setAttribute('cx',String(150+p.x*12));el('field-point').setAttribute('cy',String(240-p.z*10));};
 el('field-map').onpointerdown=e=>{const b=el('field-map').getBoundingClientRect();el<HTMLInputElement>('field-x').value=String(Math.round(((e.clientX-b.left)*300/b.width-150)/12*10)/10);el<HTMLInputElement>('field-z').value=String(Math.max(.2,Math.round((240-(e.clientY-b.top)*250/b.height)/10*10)/10));marker();};
 for(const id of ['field-x','field-z'])el(id).oninput=marker;
 const open=()=>{const p=h.game.sounding?.point??h.game.target;el<HTMLInputElement>('field-x').value=String(p.x);el<HTMLInputElement>('field-z').value=String(p.z);marker();el('field-result').textContent='Point choisi ; sondez pour mesurer le fond.';el('field-bait').innerHTML=COMPONENTS.filter(i=>i.slot==='groundbait'&&i.methods.includes(h.game.method)&&(!i.techniques||i.techniques.includes(h.game.technique.id))&&(i.free||available(h.save().tackle,i.id)>0)).map(i=>'<option value="'+i.id+'">'+i.name+' · '+(i.free?'∞':available(h.save().tackle,i.id))+' portions</option>').join('');el<HTMLButtonElement>('field-baiting').disabled=h.game.method==='lure';h.open('field-tools');};
 el('survey-open').onclick=el('groundbait').onclick=open;
 el('field-survey').onclick=()=>{el('field-result').textContent=h.game.survey(point())?'Fond : '+h.game.sounding!.depth.toFixed(1)+' m · '+h.game.sounding!.microzone+'. Réglez ensuite votre montage.':h.game.failure;};
 el('field-baiting').onclick=()=>{if(!h.game.groundbait(point(),Number(el<HTMLSelectElement>('field-portions').value),el<HTMLSelectElement>('field-bait').value)){el('field-result').textContent=h.game.failure||'Action indisponible.';return;}h.persist();h.close('field-tools');h.toast('Zone amorcée : rayon 1,8 m, 45 s ; les portions du sac ont été engagées.');};
 return ()=>{el('survey-open').hidden=!['idle','waiting'].includes(h.game.phase);};
}
