import {POND_MAP} from '../game/pond-map';
import {ALL_POSTS,postById,postLocation,worldPoint,populationWeight,type PostId} from '../game/posts';
import {postAccess,postCondition,initiateLures,methodAccess,techniqueAccess,techniqueCondition} from '../game/progression';
import {TECHNIQUES,techniqueContext} from '../game/techniques';
import {objectives,trackedObjective,destinationForPost,type ObjectiveView} from '../game/objectives';
import {BADGE_RULES} from '../game/structure';
import {BADGES} from '../game/economy';
import {SPECIES} from '../game/catalog';
import {discoveredFish} from '../game/save';
import {escapeUI as esc,groupedTechniques,installSectionTabs} from './presentation';
import type {ScreenHooks} from './structure';
const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const meter=(value:number,target:number)=>`<progress value="${Math.min(value,target)}" max="${target}"></progress><small>${Math.min(value,target)} / ${target}</small>`;
export class JourneyScreens {
 private selected:PostId='jetty';
 private progressTab='path';
 constructor(private h:ScreenHooks){
  el('app').insertAdjacentHTML('beforeend',`<dialog id="map" class="modal wide-modal"><div class="modal-header"><div><div class="eyebrow" id="map-destination"></div><h2>Mes postes</h2></div><button class="close" data-close="map">Retour</button></div><div id="local-map"></div><button id="map-other" class="secondary">Autres lieux</button><p id="map-state" class="intro" aria-live="polite"></p><article id="post-sheet"></article></dialog><dialog id="initiation" class="modal"><div class="modal-header"><h2>Premiers leurres</h2><button class="close" data-close="initiation">Retour</button></div><p class="intro">Laissez descendre le leurre, maintenez Mouliner pour le ramener, puis faites une courte pause ou un mouvement de canne. Profondeur, vitesse et trajectoire changent les rencontres. Le fil et le scion signalent la touche ; ferrez.</p><p id="initiation-state" class="intro"></p><button id="initiation-complete" class="action">J’ai compris · ouvrir le kit leurres</button></dialog>`);
  el('map-open').onclick=()=>this.h.open('map');el('map-other').onclick=()=>this.h.open('locations');
  el('map').addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLElement>('[data-post]');if(b)this.preview(b.dataset.post as PostId);});
  document.addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLElement>('[data-preview-post]');if(b){this.h.open('map');this.preview(b.dataset.previewPost as PostId);}});
  document.addEventListener('fishdex-encounter-preview',event=>{if(el<HTMLDialogElement>('map').open)this.preview((event as CustomEvent<{route:{post:PostId}}>).detail.route.post);});
  el('initiation-complete').onclick=()=>{const message=initiateLures(this.h.save());if(message){this.h.toast(message);return;}this.h.persist();this.h.refresh();this.h.close('initiation');if(el<HTMLDialogElement>('component-sheet').open){this.h.close('component-sheet');this.h.open('preparation');}this.h.toast('Kit leurres ouvert. Choisissez cette pratique dans Ma canne.');};
  el('progression').addEventListener('click',event=>{const b=(event.target as HTMLElement).closest<HTMLElement>('[data-progress-tab],[data-goal-action],[data-follow-goal],[data-goal-unfollow],[data-goal-material]');if(!b)return;if(b.dataset.progressTab){this.progressTab=b.dataset.progressTab;this.progression();}if(b.dataset.followGoal){this.h.save().ui={trackedObjective:b.dataset.followGoal};this.h.persist();this.progression();}if(b.hasAttribute('data-goal-unfollow')){delete this.h.save().ui;this.h.persist();this.progression();}if(b.dataset.goalAction){const goal=objectives(this.h.save()).find(g=>g.id===b.dataset.goalAction);if(goal){this.h.open(goal.destination);if(goal.id==='reed-bank')this.preview('reed-bank');if(goal.id.startsWith('post:'))this.preview(goal.id.slice(5) as PostId);}}if(b.hasAttribute('data-goal-material'))this.h.open('preparation');});
 }
 opened(){this.selected=this.h.game.post;this.render();}
 preview(post:PostId){if(!ALL_POSTS.some(p=>p.id===post))return;this.selected=post;this.render();}
 summary(){const goal=trackedObjective(this.h.save());return `<strong>Prochaine étape : ${esc(goal.title)}</strong><small>${esc(goal.complete?'Objectif atteint · choisir la suite dans Ma progression':goal.action)}</small>`;}
 private goalCard(goal:ObjectiveView){return `<article class="next-step"><h3>${esc(goal.title)}</h3><p class="intro">${esc(goal.consequence)}</p>${goal.paths.map((path,index)=>(index?'<p class="intro">ou</p>':'')+`<div class="goal-path"><strong>${esc(path.label)}</strong>${meter(path.value,path.target)}</div>`).join('')}<p class="intro">${goal.complete?'Acquis permanent':esc(goal.condition)}</p><button class="action" data-goal-action="${goal.id}">${esc(goal.action)}</button><button class="secondary" data-follow-goal="${goal.id}">${this.h.save().ui?.trackedObjective===goal.id?'Objectif suivi':'Suivre cet objectif'}</button></article>`;}
 progression(){
  const s=this.h.save(),host=el('practice-masteries');host.hidden=false;if(!host.querySelector('nav')){host.innerHTML=`<nav class="work-tabs" aria-label="Progression"><button data-progress-tab="path">Mon parcours</button><button data-progress-tab="techniques">Techniques</button><button data-progress-tab="badges">Badges</button></nav><div id="progress-view"></div>`;
  const nav=host.querySelector<HTMLElement>('nav')!;installSectionTabs(nav,el('progress-view'));}const nav=host.querySelector<HTMLElement>('nav')!;nav.querySelectorAll<HTMLElement>('[data-progress-tab]').forEach(b=>{const selected=b.dataset.progressTab===this.progressTab;b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1;if(selected)el('progress-view').setAttribute('aria-labelledby',b.id);});
  // installSectionTabs sets ARIA only; rendering is owned by this class, never by a rule mutation.
  const view=el('progress-view');
  if(this.progressTab==='path'){const goals=objectives(s),goal=trackedObjective(s);view.innerHTML='<h3>Mon prochain objectif</h3>'+this.goalCard(goal)+(s.ui?.trackedObjective?'<button class="secondary" data-goal-unfollow>Ne plus suivre cet objectif</button>':'')+'<h3>Prochains déblocages</h3>'+goals.filter(g=>!g.complete&&g.id!==goal.id).slice(0,3).map(g=>this.goalCard(g)).join('')+'<button class="secondary" id="progress-map">Voir mes postes</button>';el('progress-map').onclick=()=>this.h.open('map');}
  if(this.progressTab==='techniques')view.innerHTML=groupedTechniques(t=>`<article class="compact-row" data-progress-technique="${t.id}"><div><strong>${esc(t.name)}</strong><small>${s.progression.techniqueMastery?.[t.id]??0} captures · ${techniqueAccess(s,t.id)?'Ouverte':esc(techniqueCondition(s,t.id))}</small><small>${esc(t.instruction)}</small></div><button class="secondary" data-tech="${t.id}">Fiche</button>${techniqueAccess(s,t.id)?'<button class="secondary" data-goal-material>Préparer le matériel</button>':`<button class="secondary" data-follow-goal="tech:${t.id}">Suivre le déblocage</button>`}</article>`);
  if(this.progressTab==='badges')view.innerHTML=BADGE_RULES.map(b=>`<button class="objective-card" data-objective="${b.id}"><strong>◇ ${esc(BADGES[b.id as keyof typeof BADGES])}</strong><small>${esc(b.description)}</small>${meter(s.badges.includes(b.id)?b.target:b.value(s),b.target)}<span>${s.badges.includes(b.id)?'Obtenu':'En cours'} · aucune récompense à la consultation</span></button>`).join('');
  el('progress-badges').innerHTML='';
 }
 render(){
  const s=this.h.save(),g=this.h.game,p=postById(this.selected),open=postAccess(s,p.id),destination=destinationForPost(p.id),localPosts=destination.posts.map(id=>postById(id as PostId)),known=discoveredFish(s);
  el('map-destination').textContent=destination.name;
  el('local-map').innerHTML=destination.id==='willow-pond'?`<div class="pond-map" role="group" aria-label="Six postes autour de l’étang"><svg viewBox="0 0 320 220" aria-hidden="true"><path d="${POND_MAP.contour.map((point,n)=>(n?'L':'M')+(160+point.x*2)+' '+(197-(point.z+7)*1.9)).join(' ')}Z"/>${localPosts.flatMap(post=>post.obstacles.map(o=>{const w=worldPoint(post.id,o);return `<circle cx="${160+w.x*2}" cy="${197-(w.z+7)*1.9}" r="${Math.max(3,o.radius*2)}" fill="var(--fd-warning)" aria-hidden="true"/>`;})).join('')}${POND_MAP.habitats.map(zone=>`<circle cx="${160+zone.center_xz_m[0]*2}" cy="${197-(zone.center_xz_m[1]+7)*1.9}" r="${zone.radius_m*2}" fill="var(--fd-accent)" opacity=".12"/>`).join('')}</svg>${localPosts.map((post,index)=>`<button class="map-pin" style="left:${(160+post.origin.x*2)/3.2}%;top:${(197-(post.origin.z+7)*1.9)/2.2}%" data-post="${post.id}" aria-label="${post.name}">${index+1}</button>`).join('')}</div><p class="intro">Contours et postes issus du terrain du jeu. Points sable : obstacles ; plages turquoise : habitats. Touchez un repère pour lire ses contraintes.</p>`:`<div class="context-map"><span>${p.context==='river'?'Courant et dérive':p.context==='boat'?'Embarcation sur le lac':'Couches du milieu'}</span><p class="intro">Schéma des postes · pas une nouvelle étendue d’eau</p>${localPosts.map(post=>`<button class="secondary" data-post="${post.id}" aria-label="${post.name}">${post.name}</button>`).join('')}</div>`;
  el('map-state').textContent=`Poste actuel : ${postById(g.post).name} · consultation sans trajet`;
  el('map').querySelectorAll<HTMLElement>('[data-post]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.post===this.selected));b.dataset.state=postAccess(s,b.dataset.post as PostId)?'open':'locked';});
  const methods=TECHNIQUES.filter(t=>techniqueContext(t.id,p.context??'pond')),recommended=methods.filter(t=>techniqueAccess(s,t.id)).slice(0,3),fish=SPECIES.filter(f=>['margin','plants','open-water','dropoff','wood'].some(zone=>populationWeight(p.id,f.id,zone as import('../game/posts').Microzone)>0));
  el('post-sheet').innerHTML=`${destination.id==='willow-pond'?`<img class="post-preview" src="/map-assets/post-${p.id}.jpg" alt="Vue du poste ${esc(p.name)} depuis le jeu, ambiance matin" width="576" height="360" loading="lazy">`:'<div class="empty-state">Aperçu photographique non disponible · contexte de pêche existant</div>'}<h3>${esc(p.name)}</h3><span class="state-pill">${g.post===p.id?'Poste actuel':open?'Accessible':p.id==='reed-bank'?'Poste occupé':'À débloquer'}</span><p class="intro">${esc(p.hint)}</p><div class="slot-list">${p.constraints.map(c=>`<span>${esc(c)}</span>`).join('')}</div><p class="intro">Difficulté : ${esc(p.difficulty)} · liée aux contraintes ci-dessus, sans bonus de force.</p><h3>Poissons et indices locaux</h3><p class="intro">${fish.map(f=>known.has(f.id)?esc(f.name):'Poisson #'+String(f.number).padStart(3,'0')+' à découvrir').join(' · ')||'Aucune population confirmée.'}</p><h3>Techniques conseillées</h3><p class="intro">${recommended.map(t=>esc(t.name)).join(' · ')||'Technique compatible à ouvrir.'} · adaptées au ${p.context==='river'?'courant':p.context==='deep'?'milieu profond':p.context==='boat'?'contexte embarqué':'milieu de l’étang'}.</p><details><summary>Toutes les techniques adaptées</summary>${methods.map(t=>`<p class="intro">${esc(t.name)} · ${techniqueAccess(s,t.id)?'Ouverte':esc(techniqueCondition(s,t.id))}</p>`).join('')}</details>${p.id==='reed-bank'?`<div class="fisher-dialogue"><span aria-hidden="true">♟</span><p>${open?'Le pêcheur range sa ligne : « La place est à toi. Garde le fil dans le couloir entre les herbiers. »':'Le pêcheur : « Deux prises au coup dans le cercle du ponton, ou le niveau 3 : ensuite cette place reste à toi. »'}</p></div>`:''}<p class="intro">${open?'Accès permanent.':esc(postCondition(s,p.id))}</p>${!open?'<button id="post-objective" class="secondary">Voir ma progression</button>':''}${p.id==='reed-bank'&&!open?'<button id="post-go-challenge" class="secondary">Essayer le cercle au ponton</button>':''}<button id="post-select" class="action" ${!open||g.post===p.id?'disabled':''}>${g.post===p.id?'Poste actuel':open?'S’installer ici':'À débloquer'}</button><p class="warning-line" id="post-warning">${g.phase!=='idle'?'Ramenez la ligne ou terminez le combat avant de changer de poste.':''}</p>`;
  const select=(id:PostId)=>{if(!postAccess(s,id)){this.h.toast(postCondition(s,id));return;}if(!g.setPost(id)){this.h.toast('Ramenez la ligne ou terminez la prise avant de changer de poste.');return;}s.preparation.post=id;s.preparation.location=postLocation(id);this.h.postChanged?.();this.h.persist();for(const layer of ['map','locations','location-sheet','menu'])if(el<HTMLDialogElement>(layer)?.open)this.h.close(layer);this.h.toast(`${postById(id).name} · prêt à préparer la ligne.`);};
  el('post-select').onclick=()=>select(p.id);if(el('post-objective'))el('post-objective').onclick=()=>{s.ui={trackedObjective:p.id==='reed-bank'?'reed-bank':'post:'+p.id};this.h.persist();this.h.open('progression');};if(el('post-go-challenge'))el('post-go-challenge').onclick=()=>select('jetty');
  el('initiation-state').textContent=methodAccess(s,'lure')?'Pratique déjà ouverte.':s.total?'Première capture réussie : ce conseil ouvre le kit gratuit.':'Première capture requise. Le kit au coup permet cette initiation.';el<HTMLButtonElement>('initiation-complete').disabled=!s.total;
 }
}
