import { POSTS,ALL_POSTS, postById, postLocation, type PostId } from '../game/posts';
import { postAccess, postCondition, initiateLures, refreshRights, methodAccess,techniqueAccess,techniqueCondition } from '../game/progression';
import {TECHNIQUES,techniqueContext} from '../game/techniques';
import { methodName } from '../game/structure';
import type { ScreenHooks } from './structure';
const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
export class JourneyScreens {
  private selected:PostId='jetty';
  constructor(private h:ScreenHooks){
    el('app').insertAdjacentHTML('beforeend',`<dialog id="map" class="modal wide-modal"><div class="modal-header"><div><div class="eyebrow">L’étang des Saules</div><h2>Mes postes</h2></div><button class="close" data-close="map">Retour</button></div><div class="pond-map" role="group" aria-label="Six postes autour de l’étang"><svg viewBox="0 0 320 220" aria-hidden="true"><path d="M48 95Q64 35 165 30Q282 33 280 121Q269 188 167 190Q64 183 48 95Z"/><path class="map-bank" d="M55 99Q76 40 160 42M251 81Q275 122 233 168"/></svg>${POSTS.map((p,i)=>`<button class="map-pin map-pin-${i}" data-post="${p.id}" aria-label="${i+1}. ${p.name}">${i+1}</button>`).join('')}</div><div class="tools">${ALL_POSTS.filter(p=>p.context).map(p=>`<button class="secondary" data-post="${p.id}">${p.name}</button>`).join('')}</div><p id="map-state" class="intro" aria-live="polite"></p><article id="post-sheet"></article></dialog><dialog id="initiation" class="modal"><div class="modal-header"><h2>Premiers leurres</h2><button class="close" data-close="initiation">Retour</button></div><p class="intro">Laissez descendre le leurre, maintenez Mouliner pour le ramener, puis faites une courte pause ou un mouvement de canne. Profondeur, vitesse et trajectoire changent les rencontres. Le fil et le scion signalent la touche ; ferrez.</p><p id="initiation-state" class="intro"></p><button id="initiation-complete" class="action">J’ai compris · ouvrir le kit leurres</button></dialog>`);
    el('map-open').onclick=()=>this.h.open('map');
    el('map').addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLElement>('[data-post]');if(b){this.selected=b.dataset.post as PostId;this.render();}});
    el('initiation-complete').onclick=()=>{const message=initiateLures(this.h.save());if(message){this.h.toast(message);return;}this.h.persist();this.h.refresh();this.h.close('initiation');if(el<HTMLDialogElement>('component-sheet').open){this.h.close('component-sheet');this.h.open('preparation');}this.h.toast('Kit leurres ouvert. Choisissez cette pratique dans Ma canne.');};
  }
  render(){
    const s=this.h.save(),g=this.h.game;refreshRights(s);
    const p=postById(this.selected),open=postAccess(s,p.id);
    el('map-state').textContent=`Poste actuel : ${postById(g.post).name} · ${s.progression.posts.length} ouverts · sans frais de trajet`;
    el('map').querySelectorAll<HTMLElement>('[data-post]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.post===this.selected));b.dataset.state=postAccess(s,b.dataset.post as PostId)?'open':postById(b.dataset.post as PostId).implemented?'occupied':'future';});
    el('post-sheet').innerHTML=`<h3>${p.name}</h3><span class="state-pill">${open?p.difficulty:p.implemented?'Poste occupé':'À venir'}</span><p class="intro">${p.hint}</p><div class="slot-list">${p.constraints.map(c=>`<span>${c}</span>`).join('')}</div><p class="intro">Pratiques adaptées : ${TECHNIQUES.filter(t=>techniqueContext(t.id,p.context??'pond')).map(t=>t.name).join(' · ')}</p>${p.id==='reed-bank'?`<div class="fisher-dialogue"><span aria-hidden="true">♟</span><p>${open?'Le pêcheur range sa ligne : « La place est à toi. Garde le fil dans le couloir entre les herbiers. »':'Le pêcheur : « Je te laisse cette place au niveau 3 ou après deux prises au coup dans le cercle turquoise du ponton. Baisse la canne pour accompagner les départs. »'}</p></div>`:''}<p class="intro">${open?'Accès permanent enregistré.':postCondition(s,p.id)}</p>${p.id==='reed-bank'&&!open?'<button id="post-go-challenge" class="secondary">Essayer le cercle au ponton</button>':''}<button id="post-select" class="action" ${!open||g.post===p.id?'disabled':''}>${g.post===p.id?'Poste actuel':open?'M’installer ici':p.implemented?'Occupé':'À venir'}</button><p class="warning-line" id="post-warning">${g.phase!=='idle'?'Ramenez la ligne ou terminez le combat avant de changer de poste.':''}</p>`;
    const select=(id:PostId)=>{if(!g.setPost(id)){this.h.toast('Ramenez la ligne ou terminez la prise avant de changer de poste.');return;}s.preparation.post=id;s.preparation.location=postLocation(id);this.h.postChanged?.();this.h.persist();this.h.close('map');if(el<HTMLDialogElement>('locations').open)this.h.close('locations');if(el<HTMLDialogElement>('menu').open)this.h.close('menu');this.h.toast(`${postById(id).name} · prêt à préparer la ligne.`);};
    el('post-select').onclick=()=>select(p.id);
    if(el('post-go-challenge'))el('post-go-challenge').onclick=()=>select('jetty');
    el('initiation-state').textContent=methodAccess(s,'lure')?'Pratique déjà ouverte.':s.total?'Première capture réussie : ce conseil ouvre le kit gratuit.':'Première capture requise. Le kit au coup permet cette initiation.';
    el<HTMLButtonElement>('initiation-complete').disabled=!s.total;
    if(el('practice-masteries'))el('practice-masteries').innerHTML=`<h3>Mes 22 pratiques</h3>${TECHNIQUES.map(t=>`<div class="compact-row"><div><strong>${t.name}</strong><small>${s.progression.techniqueMastery?.[t.id]??0} prises · ${techniqueAccess(s,t.id)?'Ouverte':techniqueCondition(s,t.id)}</small></div></div>`).join('')}${!methodAccess(s,'lure')?'<button id="progress-initiation" class="secondary">Initiation aux leurres</button>':''}<details><summary>Maîtrises des familles conservées</summary>${(['pole','float','lure','bottom'] as const).map(m=>`<p class="intro">${methodName(m)} · ${s.progression.mastery[m]??0} prises</p>`).join('')}</details>`;
    if(el('practice-masteries'))el('practice-masteries').insertAdjacentHTML('beforeend',`<details><summary>Mes 22 techniques</summary>${TECHNIQUES.map(t=>`<div class="compact-row"><strong>${t.name}</strong><small>${s.progression.techniqueMastery?.[t.id]??0} prises · ${techniqueAccess(s,t.id)?'Ouverte':techniqueCondition(s,t.id)}</small></div>`).join('')}</details>`);
    if(el('progress-initiation'))el('progress-initiation').onclick=()=>this.h.open('initiation');
  }
}
