import {SPECIES} from '../game/catalog';
import {APPEARANCES,appearanceName} from '../game/fish-registry';
import {ITEMS} from '../game/economy';
import {component,SLOT_NAMES} from '../game/rig';
import {TECHNIQUES,techniqueFor} from '../game/techniques';
import {itemCondition} from '../game/progression';
import {emptyState,escapeUI as esc,installSectionTabs} from './presentation';
import type {Specimen} from '../game/specimens';
import type {ScreenHooks} from './structure';
const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
export function specimenArt(s:Pick<Specimen,'speciesId'|'appearanceId'>){const fish=SPECIES.find(f=>f.id===s.speciesId),image=APPEARANCES.find(a=>a.id===s.appearanceId)?.image??fish?.image;return image?`<img src="${image}" alt="Illustration de ${esc(appearanceName(s.appearanceId)??fish?.name??'ce poisson')}" width="320" height="180" loading="lazy">`:'<span class="image-fallback">Illustration indisponible</span>';}
export function specimenLabel(s:Specimen){return `${SPECIES.find(f=>f.id===s.speciesId)?.name} · ${s.length} cm · ${s.weight.toLocaleString('fr-FR')} kg · ${new Date(s.date).toLocaleDateString('fr-FR')}`;}

/** Restructures existing controls without replacing their transactions or storage. */
export function installMemories(h:ScreenHooks,retryAquarium:()=>void){
 const dialog=(id:string,title:string,body:string)=>`<dialog id="${id}" class="modal"><div class="modal-header"><h2>${title}</h2><button class="close" data-close="${id}">Retour</button></div>${body}</dialog>`;
 el('app').insertAdjacentHTML('beforeend',dialog('settings','Réglages','<section id="settings-audio" class="ui-section"><h3>Audio</h3></section><section id="settings-graphics" class="ui-section"><h3>Graphismes</h3><p class="intro">Économie : résolution réduite, cadence plafonnée à 30 images/s. Élevé : davantage de pixels et cadence libre. La fluidité dépend de l’appareil.</p></section><section id="settings-controls" class="ui-section"><h3>Commandes et accessibilité</h3><p class="intro">La canne garde sa position entre les gestes ; inverser les côtés ne change pas le combat. Les animations de menus suivent la préférence de réduction des mouvements de votre appareil.</p></section><section id="settings-storage" class="ui-section"><h3>Sauvegarde</h3><p class="intro">Cette partie reste dans ce navigateur. Le fichier contient captures, observations, stocks, favoris, réglages et progression. Les photos restent sur cet appareil ; ailleurs, un aperçu peut être régénéré. Exportez puis importez pour changer d’appareil. L’import remplace la partie du profil actif après confirmation ; aucune fusion.</p></section>')+dialog('lesson-sheet','Apprendre à pêcher','<div id="lesson-body"></div>')+dialog('aquarium-fish','Mes poissons','<p class="intro">Cinq individus au maximum. Retirer ou remplacer un favori conserve sa prise dans le carnet. Le même individu ne peut pas occuper deux places.</p><div id="aq-slots"></div><section id="aq-picker"><h3>Choisir une prise</h3><div id="aq-candidates"></div></section><div id="aq-selection"></div><div id="aq-transactions"></div>')+dialog('aquarium-decor','Décorer le bassin','<p class="intro">Changements immédiats et sauvegardés. Consulter ce panneau ne change rien ; aucun achat automatique.</p><div id="aq-decor-controls"></div><div id="aq-decor-access"></div>'));
 el('settings-audio').append(el('sound').closest('.setting-row')!);
 el('settings-graphics').append(el('quality').closest('.setting-row')!,el('water-quality').closest('.setting-row')!);
 el('settings-graphics').insertAdjacentHTML('beforeend','<p class="intro">Eau : Économe conserve le reflet simplifié ; Standard actualise un reflet réduit ; Élevé enrichit sa définition et les détails. Coût croissant, sans modifier la pêche.</p>');
 el('settings-controls').append(el('control-side').closest('fieldset')!);
 const exportRow=el('export-save').parentElement!;el('settings-storage').append(exportRow,el('save-file'),el('import-review'),el('export-before-progression'));
 el('export-save').textContent='Exporter ma progression';el('import-save').textContent='Importer une sauvegarde';el('confirm-import').textContent='Confirmer le remplacement';
 el('collection').querySelector('.modal-footnote')!.textContent='Des individus dans le carnet ; les identités et formes découvertes dans le FishDex.';
 el('collection').insertAdjacentHTML('beforeend','<button id="journal-save-link" class="text-action">Sauvegarde et transfert d’appareil</button>');el('journal-save-link').onclick=()=>h.open('settings');
 el('settings-save').remove();el('help').querySelectorAll('.help-steps,.modal-footnote,.setting-row:not(:has(#test-open)),.section-title,.intro').forEach(e=>e.remove());
 el('help').querySelector('h2')!.textContent='Apprendre à pêcher';el('help').insertAdjacentHTML('beforeend','<p class="intro">Un geste, une raison, puis une action à essayer. Ces guides expliquent les commandes ; ils ne simulent pas une partie.</p><div class="lesson-links"><button data-lesson="first">Premiers pas</button><button data-lesson="techniques">Techniques</button><button data-lesson="rig">Préparer son montage</button><button data-lesson="combat">Combat et réception</button><button data-lesson="glossary">Glossaire</button></div><details class="development-space" open><summary>Espace de développement</summary><p class="intro">Mode test : sauvegarde et portefeuille séparés de la partie normale. Les scénarios ne changent pas sa progression.</p><div id="help-development"></div></details>');
 if(el('test-open'))el('help-development').append(el('test-open').closest('.setting-row')!);
 el('help-open').innerHTML='Aide <small>Apprendre les gestes</small>';
 el('menu').querySelector('nav')!.insertAdjacentHTML('beforeend','<button id="settings-open">Réglages <small>Commandes et sauvegarde</small></button>');el('settings-open').onclick=()=>h.open('settings');
 el('caught').insertAdjacentHTML('beforeend','<p id="specimen-history" class="intro"></p>');
 const tab='<nav class="section-tabs" id="journal-tabs"><button data-journal-tab="captures">Prises</button><button data-journal-tab="observations">Observations</button></nav><div id="journal-pages"></div>';
 el('journal-controls').insertAdjacentHTML('beforebegin',tab);el('journal-controls').insertAdjacentHTML('afterbegin','<label>Rechercher un souvenir<input id="journal-query" type="search" placeholder="Poisson, poste ou technique"></label>');
 el('journal-controls').insertAdjacentHTML('beforeend','<div id="journal-active" class="filter-chips"></div>');
 el('journal-controls').querySelector('.filter-panel')!.insertAdjacentHTML('afterbegin','<p class="intro">Les filtres se combinent : un souvenir doit respecter tous les choix. Le tri reste indépendant. Retirer un filtre ne supprime aucune prise.</p>');
 const capturePage=document.createElement('section');capturePage.id='journal-captures';const obsPage=document.createElement('section');obsPage.id='journal-observations';
 el('journal-tabs').after(el('journal-controls'),el('journal-pages'));el('journal-pages').append(capturePage,obsPage);capturePage.append(el('journal-intro'),el('journal-list'),el('journal-more'),el('legacy-records'));obsPage.append(el('observation-results'),el('observation-journal'),el('observation-more'));obsPage.hidden=true;
 el('collection').querySelectorAll('.section-title').forEach(e=>e.remove());el('mastery-list').hidden=true;
 el('journal-tabs').onclick=e=>{const view=(e.target as HTMLElement).closest<HTMLElement>('[data-journal-tab]')?.dataset.journalTab;if(view){capturePage.hidden=view!=='captures';obsPage.hidden=view!=='observations';}};installSectionTabs(el('journal-tabs'),el('journal-pages'));
 el('journal-view').querySelector('[value="latest"]')!.textContent='Récentes (10 dernières)';el('journal-view').querySelector('[value="variants"]')!.textContent='Formes';
 el('journal-controls').addEventListener('click',e=>{const id=(e.target as HTMLElement).closest<HTMLElement>('[data-clear-filter]')?.dataset.clearFilter;if(id){const c=el<HTMLInputElement>(id);if(c.type==='checkbox')c.checked=false;else c.value='';h.refresh();}});
 el('aquarium-canvas').insertAdjacentHTML('afterend','<div class="aquarium-actions"><button id="aq-fish-open" class="action">Mes poissons</button><button id="aq-decor-open" class="secondary">Décorer</button><button id="aq-retry" class="text-action" hidden>Réessayer la 3D</button></div>');
 el('aq-retry').onclick=retryAquarium;
 el('aq-transactions').append(el('aquarium-choice').parentElement!,el('aq-replace-slot').closest('.filters')!);el('aq-decor-controls').append(el('aq-floor').closest('.aquarium-settings')!);el('aq-decor-access').append(el('aq-shop'));
 el('aquarium-choice').parentElement!.classList.add('aquarium-compact-selector');el('aquarium-choice').setAttribute('aria-label','Prise choisie (longueur et date)');
 el('aq-slots').append(el('aquarium-favorites'));el('aquarium').querySelector('.section-title')?.remove();el('aquarium').querySelector('.modal-footnote')!.textContent='Vos poissons nagent à leur taille et dans leur robe enregistrées. Aucun entretien ni pénalité d’absence.';
 el('aq-fish-open').onclick=()=>{refresh();h.open('aquarium-fish');};el('aq-decor-open').onclick=()=>{refresh();h.open('aquarium-decor');};
 document.addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLElement>('[data-aq-choose],[data-lesson],[data-help-component],[data-help-technique],[data-return-fishing]');if(!b)return;if(b.dataset.aqChoose){el<HTMLSelectElement>('aquarium-choice').value=b.dataset.aqChoose;refreshSelection();}if(b.dataset.lesson)lesson(b.dataset.lesson);if(b.dataset.helpComponent)lesson('component',b.dataset.helpComponent);if(b.dataset.helpTechnique)lesson('technique',b.dataset.helpTechnique);if(b.hasAttribute('data-return-fishing'))document.querySelectorAll<HTMLDialogElement>('dialog[open]').forEach(d=>d.close());});
 function refreshSelection(){const id=el<HTMLSelectElement>('aquarium-choice').value,s=h.save().journal.find(s=>s.id===id);el('aq-selection').innerHTML=s?`<p class="intro">Choisi : ${esc(specimenLabel(s))}. ${h.save().favorites.length===5?'Bassin plein : choisissez explicitement l’emplacement à remplacer ci-dessous.':'Ajoutez-le avec le bouton Ajouter.'}</p>`:emptyState('Aucune prise éligible','Capturez un poisson pour lui offrir une place.')+'<button class="secondary" data-return-fishing>Retourner pêcher</button>';el('aq-candidates').querySelectorAll('[data-aq-choose]').forEach(b=>b.setAttribute('aria-pressed',String((b as HTMLElement).dataset.aqChoose===id)));}
 el('aquarium-choice').addEventListener('change',refreshSelection);
 let candidateLimit=24;el('aq-picker').insertAdjacentHTML('beforeend','<button id="aq-more" class="secondary">Prises suivantes</button>');el('aq-more').onclick=()=>{candidateLimit+=24;refresh();};
 function refresh(){const s=h.save();el('aq-more').hidden=s.journal.filter(f=>!s.favorites.includes(f.id)).length<=candidateLimit;el('aq-candidates').innerHTML=s.journal.filter(f=>!s.favorites.includes(f.id)).slice().reverse().slice(0,candidateLimit).map(f=>`<button class="aq-candidate" data-aq-choose="${esc(f.id)}">${specimenArt(f)}<span>${esc(specimenLabel(f))}<small>${esc(appearanceName(f.appearanceId)??(f.coloration==='golden'?'Reflets dorés':'Robe naturelle'))}</small></span></button>`).join('')||emptyState(s.journal.length?'Toutes vos prises sont déjà favorites':'Aucune prise dans le carnet','Une observation reste un souvenir, sans devenir un poisson du bassin.');refreshSelection();let access=el('aq-decor-status');if(!access){el('aq-decor-access').insertAdjacentHTML('afterbegin','<div id="aq-decor-status"></div>');access=el('aq-decor-status');}access.innerHTML=['plants','rocks'].map(id=>{const i=ITEMS.find(i=>i.id===id)!;return `<p class="intro"><strong>${i.name}</strong> · ${s.inventory.includes(i.id)?'Possédé, choisissez son interrupteur':`${i.price} écus · ${itemCondition(s,id)||'Disponible en boutique'}`}</p>`;}).join('');
  const records=Object.keys(s.records).length;el('legacy-records').querySelector('summary')!.textContent=`Records historiques et d’identités (${records})`;el<HTMLDetailsElement>('legacy-records');
  if(!el('legacy-explanation'))el('legacy-records').insertAdjacentHTML('afterbegin','<p id="legacy-explanation" class="intro">Les records restent conservés même sans prise individuelle détaillée. Un record seul ne peut pas devenir un favori : aucun poisson fictif n’est créé.</p>');
  for(const [id,values] of [['journal-species',new Set(s.journal.map(f=>f.speciesId).concat(s.observations.map(o=>o.speciesId)))],['journal-variant',new Set([...s.journal.map(f=>f.appearanceId??f.coloration),...s.observations.map(o=>o.appearanceId??'natural'),'mirage'])],['journal-method',new Set(s.journal.flatMap(f=>[f.method,f.technique??'']))],['journal-post',new Set([...s.journal.map(f=>f.post??''),...s.observations.map(o=>o.post)])],['journal-recipe',new Set(s.journal.map(f=>f.recipe??''))],['journal-location',new Set([...s.journal.map(f=>f.location),...s.observations.map(o=>importPostName(o.post))])]] as const){for(const opt of el<HTMLSelectElement>(id).options)opt.hidden=!!opt.value&&!Array.from(values).includes(opt.value as never)&&!opt.selected;}
  const controls=[...el('journal-controls').querySelectorAll<HTMLInputElement|HTMLSelectElement>('input,select')].filter(c=>c.id!=='journal-sort'&&c.id!=='journal-view'&&(c.type==='checkbox'?(c as HTMLInputElement).checked:!!c.value));el('journal-active').innerHTML=controls.map(c=>`<button class="text-action" data-clear-filter="${c.id}">${esc(c.closest('label')?.firstChild?.textContent??'Filtre')} : ${esc(c instanceof HTMLSelectElement?c.selectedOptions[0]?.textContent??c.value:c.type==='checkbox'?'Oui':c.value)} ×</button>`).join('');
  el('aquarium-open').innerHTML=`Aquarium <small>${s.favorites.length?s.favorites.length+' / 5 individus':'Un bassin à peupler avec vos prises'}</small>`;el('shop-open').innerHTML='Boutique <small>Équipements, consommables et décors</small>';el('locations-open').innerHTML='Lieux et carte <small>Choisir un habitat et un poste</small>';el('equipment-open').innerHTML=`Matériel <small>${esc(techniqueFor(s.tackle.config).name)}</small>`;
 }
 function importPostName(id:import('../game/posts').PostId){return ALL_POSTS.find(p=>p.id===id)?.name??'';}
 function lesson(topic:string,id?:string){const t=TECHNIQUES.find(t=>t.id===id)??techniqueFor(h.save().tackle.config),side=h.save().settings.controls?.side??'left',opposite=side==='left'?'droite':'gauche';const gesture='<svg class="lesson-gesture" viewBox="0 0 200 90" role="img" aria-label="Geste du bas vers l’eau"><path d="M15 25Q70 10 180 25M15 35Q70 20 180 35M70 78L115 32M100 36L115 32L112 47" fill="none" stroke="currentColor" stroke-width="3"/></svg>';let title='Premiers pas',body=`${gesture}<p>Choisissez le matériel et un poste accessible. Pour lancer, partez du tiers inférieur, glissez vers l’eau puis relâchez au centre ou plus haut. Un geste hors du secteur annule le lancer.</p><p>Surveillez ${esc(t.signal.toLocaleLowerCase())} et ferrez la prise. Une inspection du poisson n’est pas encore une touche.</p><button class="action" data-return-fishing>Essayer au bord de l’eau</button>`;
  if(topic==='techniques'){title='Les techniques';body=TECHNIQUES.map(t=>`<button class="lesson-choice" data-help-technique="${t.id}">${esc(t.name)}<small>${esc(t.signal)}</small></button>`).join('');}
  if(topic==='technique'){title=t.name;body=gesture+`<p>${esc(t.instruction)}</p><p>Touche : ${esc(t.signal)}. ${t.reel?'Maintenir Mouliner récupère ; relâcher arrête immédiatement.':'Sans moulinet : accompagnez le départ avec la canne, puis relevez progressivement.'}</p><p>${t.sections?'Déboîtez lorsque la jonction est accessible, sans retirer de fil.':'La présentation et les gestes de canne gardent le contact avec le montage.'}</p><button class="secondary" id="lesson-material">Voir mon matériel</button>`;}
  if(topic==='rig'||topic==='component'){const c=id?component(id):undefined;title=c?.name??'Préparer son montage';body=(c?`<p>${esc(c.description)}</p><p>Emplacement : ${esc(SLOT_NAMES[c.slot])} · ${c.free?'composant gratuit et renouvelable':'stock engagé au lancer, pertes selon l’issue réelle'}.</p>`:'')+`<p>Ma canne détermine les techniques compatibles. Le montage indique chaque pièce et l’immersion. Consultez la cause d’une incompatibilité avant de remplacer une pièce.</p><p>Stock manquant : utilisez le kit gratuit ou achetez un lot compatible. Profondeur impossible : sondez puis adaptez l’immersion au fond et à la portée. Un achat n’équipe pas la pièce.</p><p>Technique actuelle : ${esc(t.name)}. ${esc(t.instruction)}</p>`;}
  if(topic==='combat'){title='Combat et réception';body=gesture+`<p>Canne à ${side==='left'?'gauche':'droite'} ; ${t.reel?'moulinet à '+opposite+' par appui maintenu':'coup sans moulinet'}. ${h.save().settings.controls?.singleFinger?'Un doigt : alternez canne et récupération.':'Deux commandes indépendantes peuvent être utilisées ensemble.'}</p><p>Accompagnez les départs, gardez le contact sans surcharger le fil. Le frein rend du fil sous résistance. Récupérez le mou au retour du poisson ; sans moulinet, baissez puis relevez la canne.</p><p>À portée, placez la tête de réception sous la prise puis faites un court geste vers le haut. La casse perd les composants réellement concernés ; la réparation et le kit gratuit restent dans Matériel.</p>`;}
  if(topic==='glossary'){title='Glossaire';body='<dl><dt>Esche</dt><dd>Appât porté par l’hameçon.</dd><dt>Amorce</dt><dd>Nourriture déposée pour attirer localement ; aucune capture garantie.</dd><dt>Bas de ligne</dt><dd>Partie terminale entre fil principal et hameçon.</dd><dt>Frein</dt><dd>Résistance du moulinet qui laisse sortir du fil.</dd><dt>Ferrage</dt><dd>Geste au moment de la prise, après le signal de touche.</dd><dt>Microzone</dt><dd>Bordure, herbier, eau ouverte, cassure ou bois : habitat et contraintes réels du point de chute.</dd></dl>';}
  el('lesson-sheet').querySelector('h2')!.textContent=title;el('lesson-body').innerHTML=body;const material=el('lesson-material');if(material)material.onclick=()=>h.open('preparation');h.open('lesson-sheet');
 }
 const nav=el('menu').querySelector('nav')!;const dex=el('dex-open');nav.prepend(dex);const groups=[['Préparer et explorer',['equipment-open','locations-open','observe-open']],['Ma collection',['collection-open','aquarium-open']],['Mon parcours',['progress-open','shop-open']],['Utilitaires',['settings-open','help-open']]] as const;for(const [name,ids] of groups){const section=document.createElement('section');section.className='menu-group';section.innerHTML=`<h3>${name}</h3><div class="menu-group-links"></div>`;for(const id of ids)section.lastElementChild!.append(el(id));nav.append(section);}el('menu').querySelector('h2')!.textContent='Au bord de l’eau';
 refresh();return {refresh,lesson};
}
import {ALL_POSTS} from '../game/posts';
