import {postAccess,postCondition} from '../game/progression';
import {filterObservations,type JournalFilter} from '../game/structure';
import {appearanceName} from '../game/fish-registry';
import {SPECIES} from '../game/catalog';
import {ObservationSession,type Observation} from '../game/observations';
import {ALL_POSTS,observationPopulation,postById} from '../game/posts';
import {discoveredFish,recordObservation} from '../game/save';
import {FishPreview} from '../render/fish-preview';
import {ZERO_REWARD,type Specimen} from '../game/specimens';
import {storePhoto,getPhoto} from './photos';
import type {ScreenHooks} from './structure';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
export function installObservations(h:ScreenHooks){
 el('menu').querySelector('nav')!.insertAdjacentHTML('beforeend','<button id="observe-open">Observer les poissons<small>Découvertes sans hameçon</small></button>');
 el('app').insertAdjacentHTML('beforeend',`<dialog id="observation" class="modal"><div class="modal-header"><h2>Observer sans pêcher</h2><button class="close" data-close="observation">Retour</button></div><p id="observation-habitat" class="intro"></p><label>Poisson de cet habitat<select id="observation-species"></select></label><button id="observation-start" class="secondary">Chercher ce poisson</button><canvas id="observation-preview" class="observation-preview" width="480" height="240" hidden></canvas><p id="observation-state" class="intro" aria-live="polite"></p><progress id="observation-progress" max="12" value="0"></progress><button id="observation-hold" class="action" disabled>Maintenir pour suivre le poisson</button><button id="observation-photo" class="secondary" disabled>Photographier l’observation</button><p class="intro">Suivez-le pendant 12 secondes cumulées. Le relâchement arrête l’effort. La première découverte donne 20 XP, une nouvelle robe 5 XP, aucun gain répétable en écus et aucun favori d’aquarium.</p></dialog>`);
 el('observation-state').insertAdjacentHTML('afterend','<div id="observation-destinations"></div>');
 let session:ObservationSession|undefined,preview:FishPreview|undefined,request=0,selected:Observation|undefined,last=0;
 const stop=()=>{session?.release();};
 const reset=()=>{request++;session?.cancel();session=undefined;preview?.dispose();preview=undefined;selected=undefined;el('observation-preview').hidden=true;el<HTMLButtonElement>('observation-photo').disabled=true;el<HTMLButtonElement>('observation-hold').disabled=true;el<HTMLProgressElement>('observation-progress').value=0;};
 const render=()=>{el('observation-habitat').textContent=postById(h.game.post).name;const fish=observationPopulation(h.game.post);el('observation-species').innerHTML=fish.map(s=>`<option value="${s.id}">${discoveredFish(h.save()).has(s.id)?esc(s.name):'Poisson à découvrir #'+s.number}</option>`).join('')||'<option value="">Aucun poisson à observer ici</option>';el<HTMLButtonElement>('observation-start').disabled=!fish.length||h.game.phase!=='idle';el('observation-state').textContent=fish.length?'Cherchez dans l’habitat avant de suivre la silhouette.':'Consultez un habitat ci-dessous pour préparer une observation.';el('observation-destinations').innerHTML=fish.length?'':ALL_POSTS.filter(p=>observationPopulation(p.id).length>0).sort((a,b)=>Number(postAccess(h.save(),b.id))-Number(postAccess(h.save(),a.id))).slice(0,4).map(p=>`<article class="next-step"><strong>${esc(p.name)}</strong><p class="intro">${postAccess(h.save(),p.id)?'Accessible · poissons à observer':esc(postCondition(h.save(),p.id))}</p><button class="secondary" data-preview-post="${p.id}">Voir cet habitat</button></article>`).join('');};
 el('observe-open').onclick=()=>{if(h.game.phase!=='idle'){h.toast('Ramenez la ligne avant l’observation.');return;}reset();render();h.open('observation');};
 el('observation-start').onclick=async()=>{
  if(h.game.phase!=='idle')return;reset();const id=el<HTMLSelectElement>('observation-species').value,fish=SPECIES.find(s=>s.id===id);if(!fish)return;
  try{const dev=!!h.save().development,seed=dev?Number(el<HTMLInputElement>('test-seed').value):crypto.getRandomValues(new Uint32Array(1))[0];session=new ObservationSession(h.game.post,id,seed,Math.random,dev?{appearanceId:el<HTMLSelectElement>('test-appearance').value||'natural',length:Number(el<HTMLInputElement>('test-length').value)}:undefined);const token=request,o=session.specimen;selected=o;el('observation-preview').hidden=false;preview=new FishPreview(el<HTMLCanvasElement>('observation-preview'));const display:Specimen={...o,form:'common',coloration:'natural',mirage:false,location:postById(o.post).name,method:'float',equipment:'starter',bait:'worm',controlled:false,reward:ZERO_REWARD()};const ok=await preview.show(fish,display);if(token!==request)return;el<HTMLButtonElement>('observation-hold').disabled=!ok;el('observation-state').textContent=ok?'Poisson repéré. Maintenez pour suivre sa nage.':'Aperçu indisponible ; réessayez.';}catch(e){h.toast(String(e));}
 };
 const hold=el('observation-hold');hold.onpointerdown=e=>{if(!session||session.complete)return;e.preventDefault();hold.setPointerCapture(e.pointerId);session.holding=true;};
 for(const name of ['pointerup','pointercancel','lostpointercapture'])hold.addEventListener(name,stop);
 hold.onkeydown=e=>{if((e.key===' '||e.key==='Enter')&&session&&!session.complete){e.preventDefault();session.holding=true;}};hold.onkeyup=stop;
 const dialog=el<HTMLDialogElement>('observation');document.addEventListener('fishing-input-reset',()=>{stop();if(dialog.open)preview?.pause();});dialog.addEventListener('focusin',()=>preview?.resume());dialog.addEventListener('close',reset);window.addEventListener('blur',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();preview?.pause();}else if(dialog.open)preview?.resume();});window.addEventListener('pagehide',reset);
 const tick=(now:number)=>{const dt=last?(now-last)/1000:0;last=now;if(dialog.open&&session&&!document.hidden){session.step(dt);el<HTMLProgressElement>('observation-progress').value=session.elapsed;if(session.complete){session.release();el<HTMLButtonElement>('observation-hold').disabled=true;el<HTMLButtonElement>('observation-photo').disabled=false;el('observation-state').textContent='Observation terminée. Photographiez pour conserver la découverte.';}}requestAnimationFrame(tick);};requestAnimationFrame(tick);
 el('observation-photo').onclick=async()=>{if(!session?.complete||!selected||!preview)return;const o=selected,token=request;el<HTMLButtonElement>('observation-photo').disabled=true;const blob=await preview.photo();if(token!==request)return;if(!blob){h.toast('Photo indisponible ; recommencez la prise de vue.');el<HTMLButtonElement>('observation-photo').disabled=false;return;}const first=!discoveredFish(h.save()).has(o.speciesId),newForm=!!o.appearanceId&&!h.save().observations.some(x=>x.appearanceId===o.appearanceId);if(recordObservation(h.save(),o)){if(first||newForm)document.dispatchEvent(new CustomEvent('fishdex-discovery',{detail:{id:o.speciesId}}));const stored=await storePhoto(o.id,blob);h.persist();h.refresh();h.toast(`Observation conservée · +${h.save().observations.find(x=>x.id===o.id)?.xp??0} XP${stored?' · photo sauvegardée':' · photo non conservée'}`);}el('observation-state').textContent='Découverte et identité conservées dans le carnet. Aucun poisson ajouté à l’aquarium.';session=undefined;};
 el('collection').insertAdjacentHTML('beforeend','<h3 class="section-title">Mes observations</h3><p id="observation-results" class="intro" aria-live="polite"></p><div id="observation-journal"></div>');
 let limit=24;el('observation-journal').insertAdjacentHTML('afterend','<button id="observation-more" class="secondary">Voir les observations précédentes</button>');
 const journal=(filter:JournalFilter={})=>{const s=h.save(),target=el('observation-journal'),rows=filterObservations(s,filter);el('observation-more').hidden=rows.length<=limit;el('observation-results').textContent=`${rows.length} observation(s) filtrée(s) sur ${s.observations.length}`;target.innerHTML=rows.slice(0,limit).map(o=>`<article class="specimen-card"><button class="specimen-view" data-observation="${esc(o.id)}"><div class="photo-placeholder" data-observation-photo="${esc(o.id)}">Photo d’observation</div><div><strong>${SPECIES.find(f=>f.id===o.speciesId)?.name}</strong><p>${o.length} cm · ${o.weight.toLocaleString('fr-FR')} kg · ${esc(appearanceName(o.appearanceId)??'Robe naturelle')} · observation · ${postById(o.post).name}</p><small>${new Date(o.date).toLocaleString('fr-FR')} · sans capture</small></div></button></article>`).join('')||'<p class="intro">Aucune observation conservée.</p>';for(const o of rows.slice(0,limit)){void getPhoto(o.id).then(blob=>{const node=target.querySelector(`[data-observation-photo="${CSS.escape(o.id)}"]`);if(!blob||!node)return;const url=URL.createObjectURL(blob),img=new Image();img.alt='Photo 3D d’observation';img.src=url;img.onload=()=>URL.revokeObjectURL(url);node.replaceChildren(img);});}};
 el('observation-more').onclick=()=>{limit+=24;h.refresh();};
 el('collection').addEventListener('click',e=>{const id=(e.target as HTMLElement).closest<HTMLElement>('[data-observation]')?.dataset.observation;if(!id)return;const o=h.save().observations.find(o=>o.id===id);if(!o)return;reset();render();el<HTMLSelectElement>('observation-species').innerHTML=`<option value="${o.speciesId}">${SPECIES.find(s=>s.id===o.speciesId)?.name}</option>`;el<HTMLButtonElement>('observation-start').disabled=true;el('observation-preview').hidden=false;h.open('observation');preview=new FishPreview(el<HTMLCanvasElement>('observation-preview'));void preview.show(SPECIES.find(s=>s.id===o.speciesId)!,{...o,form:'common',coloration:'natural',mirage:false,location:postById(o.post).name,method:'float',equipment:'starter',bait:'worm',controlled:false,reward:ZERO_REWARD()}).then(async(ok)=>{const token=request;if(ok&&!await getPhoto(o.id)&&token===request){const blob=await preview?.photo();if(blob&&token===request)await storePhoto(o.id,blob);}});el('observation-state').textContent=`Souvenir du ${new Date(o.date).toLocaleString('fr-FR')} · ${postById(o.post).name} · ${o.length} cm. Aucune nouvelle récompense.`;});
 return {journal,open:()=>el('observe-open').click()};
}
