import type {ScreenHooks} from './structure';
import type {LakeWorld} from '../render/world';
import {POSTS,postLocation} from '../game/posts';
import {WATER_TYPES,type WaterType} from '../game/water-events';
import type {WaterQuality} from '../render/pond-water';
const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
export function installWaterTools(h:ScreenHooks,getWorld:()=>LakeWorld|undefined){
 el('quality').closest('.setting-row')!.insertAdjacentHTML('afterend','<label class="setting-row">Rendu de l’eau<select id="water-quality"><option value="low">Économe</option><option value="standard">Standard</option><option value="high">Élevé</option></select></label>');
 el<HTMLSelectElement>('water-quality').value=h.save().settings.waterQuality??'low';el('water-quality').onchange=()=>{h.save().settings.waterQuality=el<HTMLSelectElement>('water-quality').value as WaterQuality;getWorld()?.setWaterQuality(h.save().settings.waterQuality!);h.persist();};
 el('test-scenarios').insertAdjacentHTML('afterbegin','<button id="water-tools-open" class="secondary">Carte et eau · essais visuels</button>');
 el('app').insertAdjacentHTML('beforeend',`<dialog id="water-tools" class="modal detail-modal"><div class="modal-header"><h2>Carte et eau</h2><button class="close" data-close="water-tools">Retour</button></div><p class="intro">Profil TEST uniquement. Les effets isolés ne créent aucune touche, capture ni récompense. Fermer ce panneau reprend l’horloge ; un menu la gèle.</p><div class="filters"><label>Poste<select id="water-post">${POSTS.map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}</select></label><label>Qualité<select id="water-profile"><option value="low">Bas</option><option value="standard">Standard</option><option value="high">Haut</option></select></label><label>Ambiance visuelle<select id="water-ambience"><option value="morning">Matin doux</option><option value="overcast">Jour couvert</option><option value="evening">Fin de journée</option></select></label></div><label class="setting-row">Profondeurs, habitats, obstacles et secteurs<input id="water-overlays" type="checkbox"></label><label>Graine visuelle<input id="water-seed" type="number" min="0" max="4294967295" step="1" value="127"></label><label>Événement isolé<select id="water-event">${WATER_TYPES.map(t=>`<option>${t}</option>`).join('')}</select></label><div class="tools"><button id="water-event-play">Voir cet effet</button><button id="water-stress">30 impacts isolés</button><button id="water-calm">Eau au repos</button></div><details><summary>Remplacement d’une famille</summary><p class="intro">GLB futur sous /models/environment/. Un fichier absent ou invalide conserve le décor. Collisions et prises ne changent pas.</p><label>Famille<select id="water-family"></select></label><label>Fichier<input id="water-resource" type="text" placeholder="/models/environment/env_tree_alder_v01_lod0.glb"></label><button id="water-replace">Charger et contrôler</button><button id="water-fallback">Revenir au provisoire</button><p id="water-asset-state"></p></details><details open><summary>Mesures et ressources</summary><pre id="water-diagnostics"></pre></details></dialog>`);
 const diagnostics=()=>{const w=getWorld();if(!w)return;el('water-diagnostics').textContent=JSON.stringify({post:h.game.post,clock:h.game.simulationTime,seed:h.game.specimenSeed??127,...w.waterDiagnostics(),render:w.renderDiagnostics()},null,2);};
 const close=()=>{h.close('water-tools');for(const id of ['test-tools','help','menu'])if(el<HTMLDialogElement>(id).open)h.close(id);};
 el('water-tools-open').onclick=()=>{if(!h.game.testMode)return;el<HTMLSelectElement>('water-post').value=h.game.post;const w=getWorld();el('water-family').innerHTML=[...new Set(w?.pondScenery.placements.map(p=>p.family))].map(id=>`<option>${id}</option>`).join('');h.open('water-tools');diagnostics();};
 el('water-post').onchange=()=>{const id=el<HTMLSelectElement>('water-post').value as typeof h.game.post;if(!h.game.setPost(id)){h.toast('Ramenez le montage avant de changer de poste.');return;}h.save().preparation.post=id;h.save().preparation.location=postLocation(id);h.postChanged?.();h.persist();diagnostics();};
 el('water-profile').onchange=()=>{getWorld()?.setWaterQuality(el<HTMLSelectElement>('water-profile').value as WaterQuality);diagnostics();};el('water-ambience').onchange=()=>{getWorld()?.setAmbience(el<HTMLSelectElement>('water-ambience').value as 'morning'|'overcast'|'evening');diagnostics();};el('water-overlays').onchange=()=>getWorld()?.showMapDebug(el<HTMLInputElement>('water-overlays').checked);
 el('water-event-play').onclick=()=>{const seed=Number(el<HTMLInputElement>('water-seed').value);if(!Number.isInteger(seed)||seed<0||seed>4294967295){h.toast('Graine entière entre 0 et 4294967295.');return;}getWorld()?.waterDemo(el<HTMLSelectElement>('water-event').value as WaterType,seed);close();};el('water-stress').onclick=()=>{for(let n=0;n<30;n++)getWorld()?.waterDemo('cast_impact');close();};el('water-calm').onclick=()=>{getWorld()?.pondWater.clearEffects();close();};
 const replace=async(fallback=false)=>{const ok=await getWorld()?.pondScenery.replace(el<HTMLSelectElement>('water-family').value,fallback?null:el<HTMLInputElement>('water-resource').value);el('water-asset-state').textContent=ok?'Famille actualisée.':'Décor provisoire conservé ; consulter le diagnostic.';getWorld()?.pondWater.refresh();diagnostics();};el('water-replace').onclick=()=>void replace();el('water-fallback').onclick=()=>void replace(true);
 window.setInterval(()=>{if(el<HTMLDialogElement>('water-tools').open)diagnostics();},500);
}
