import {Scene} from '@babylonjs/core/scene';
import {Mesh} from '@babylonjs/core/Meshes/mesh';
import {VertexData} from '@babylonjs/core/Meshes/mesh.vertexData';
import {ShaderMaterial} from '@babylonjs/core/Materials/shaderMaterial';
import {StandardMaterial} from '@babylonjs/core/Materials/standardMaterial';
import {RawTexture} from '@babylonjs/core/Materials/Textures/rawTexture';
import {MirrorTexture} from '@babylonjs/core/Materials/Textures/mirrorTexture';
import {Effect} from '@babylonjs/core/Materials/effect';
import {Plane} from '@babylonjs/core/Maths/math.plane';
import {Vector3} from '@babylonjs/core/Maths/math.vector';
import {Color3} from '@babylonjs/core/Maths/math.color';
import {MeshBuilder} from '@babylonjs/core/Meshes/meshBuilder';
import {POND_MAP,pondDepth,shoreDistance,inPond} from '../game/pond-map';
import type {WaterEvent,WaterType} from '../game/water-events';
export type WaterQuality='low'|'standard'|'high';
export const WATER_PROFILES={low:{rings:12,drops:16,mirror:0,cadence:0},standard:{rings:20,drops:32,mirror:256,cadence:6},high:{rings:28,drops:48,mirror:512,cadence:3}};
export class PondWater{
 readonly mesh:Mesh;readonly contextMesh:Mesh;readonly material:ShaderMaterial;private depthTexture!:RawTexture;private mirror?:MirrorTexture;private quality:WaterQuality='low';private effects:{mesh:Mesh;event?:WaterEvent;drop?:number}[]=[];private lastId=0;private debugId=-1;private now=0;private context=false;private simple:StandardMaterial;readonly counts:Partial<Record<WaterType,number>>={};onEvent?:(e:WaterEvent)=>void;
 constructor(private scene:Scene,private reflectors:Mesh[]){
  const c=POND_MAP.contour,p=[0,0,39],idx:number[]=[],normals:number[]=[],uv:number[]=[];for(const v of c)p.push(v.x,0,v.z);for(let i=0;i<c.length;i++)idx.push(0,i+1,(i+1)%c.length+1);for(let n=0;n<p.length/3;n++){normals.push(0,1,0);uv.push(p[n*3]/8,p[n*3+2]/8);}const v=new VertexData();v.positions=p;v.indices=idx;v.normals=normals;v.uvs=uv;this.mesh=new Mesh('water',scene);v.applyToMesh(this.mesh);
  Effect.ShadersStore.pondWaterVertexShader=`precision highp float;attribute vec3 position;uniform mat4 worldViewProjection;uniform mat4 world;varying vec3 wp;varying vec4 clip;void main(){wp=(world*vec4(position,1.)).xyz;clip=worldViewProjection*vec4(position,1.);gl_Position=clip;}`;
  Effect.ShadersStore.pondWaterFragmentShader=`precision highp float;varying vec3 wp;varying vec4 clip;uniform float time;uniform vec3 eye;uniform float mirrorOn;uniform float wind;uniform float contextDepth;uniform vec3 sky;uniform sampler2D depthMap;uniform sampler2D reflection;
  float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1.,0.)),f.x),mix(hash(i+vec2(0.,1.)),hash(i+vec2(1.)),f.x),f.y);}
  void main(){vec2 p=wp.xz;vec2 info=texture2D(depthMap,vec2((p.x+90.)/180.,(p.y+31.)/140.)).rg;float depth=contextDepth>0.?contextDepth:info.r*8.;float shore=contextDepth>0.?1.:smoothstep(0.,.13,info.g);float n=noise(p*.17+vec2(time*.012,-time*.019));float a=dot(p,vec2(.75,1.12))+time*(.25+abs(wind)*.2)+n*2.,b=dot(p,vec2(-1.9,.84))-time*.41;vec3 normal=normalize(vec3(cos(a)*.035+cos(b)*.014,1.,cos(a)*.048-cos(b)*.018)*vec3(shore,1.,shore));vec3 view=normalize(eye-wp);float fres=pow(1.-max(0.,dot(view,normal)),3.);vec3 shallow=vec3(.31,.34,.21),deep=vec3(.095,.19,.18);vec3 col=mix(shallow,deep,1.-exp(-depth*.65));col+=(noise(p*1.7+vec2(time*.026,n))-.5)*.018;vec3 env=mix(vec3(.29,.38,.29),sky,n*.25+.55);vec2 ruv=clip.xy/max(.001,clip.w)*.5+.5+normal.xz*.008;vec3 reflected=texture2D(reflection,clamp(ruv,vec2(.005),vec2(.995))).rgb;env=mix(env,reflected,mirrorOn*.7);col=mix(col,env,fres*.64);float glint=pow(max(0.,dot(reflect(-normalize(vec3(-.65,.8,.4)),normal),view)),64.);col+=vec3(.72,.67,.46)*glint*.1;gl_FragColor=vec4(col,.78+.22*smoothstep(.15,2.,depth));}`;
  this.material=new ShaderMaterial('pond-water',scene,{vertex:'pondWater',fragment:'pondWater'},{attributes:['position'],uniforms:['worldViewProjection','world','time','eye','mirrorOn','wind','contextDepth','sky'],samplers:['depthMap','reflection'],needAlphaBlending:true});this.material.backFaceCulling=false;this.material.setFloat('mirrorOn',0);this.material.setFloat('wind',0);this.material.setFloat('contextDepth',0);this.material.setColor3('sky',Color3.FromHexString('#b8c9ca'));const pixels=new Uint8Array(128*128*4);for(let y=0;y<128;y++)for(let x=0;x<128;x++){const point={x:-90+(x+.5)/128*180,z:-31+(y+.5)/128*140},at=(y*128+x)*4;pixels[at]=Math.round(pondDepth(point)/8*255);pixels[at+1]=Math.round(Math.min(1,shoreDistance(point)/12)*255);pixels[at+3]=255;}const tex=RawTexture.CreateRGBATexture(pixels,128,128,scene,false,false);tex.gammaSpace=false;this.depthTexture=tex;this.material.setTexture('depthMap',tex);this.material.setTexture('reflection',tex);this.mesh.material=this.material;this.mesh.isPickable=false;this.contextMesh=MeshBuilder.CreateGround('context-water',{width:40,height:50},scene);this.contextMesh.position.z=12;this.contextMesh.material=this.material;this.contextMesh.setEnabled(false);
  this.simple=new StandardMaterial('water-comparison-simple',scene);this.simple.diffuseColor=Color3.FromHexString('#304c42');this.simple.specularColor=Color3.FromHexString('#182a24');
  const mat=new StandardMaterial('water-contact',scene);mat.disableLighting=true;mat.emissiveColor=Color3.FromHexString('#b7c7a6');mat.alpha=.22;mat.backFaceCulling=false;for(let n=0;n<28;n++){const mesh=MeshBuilder.CreateTorus('water-contact-'+n,{diameter:1,thickness:.008,tessellation:24},scene);mesh.material=mat.clone('water-contact-mat-'+n);mesh.setEnabled(false);this.effects.push({mesh});}for(let n=0;n<48;n++){const mesh=MeshBuilder.CreateSphere('water-drop-'+n,{diameter:.035,segments:4},scene);mesh.material=mat;mesh.setEnabled(false);this.effects.push({mesh,drop:n});}
 }
 setQuality(q:WaterQuality){this.quality=q;this.effects.forEach((e,n)=>{if(n>=WATER_PROFILES[q].rings&&n<28||n>=28+WATER_PROFILES[q].drops){e.event=undefined;e.mesh.setEnabled(false);}});const p=WATER_PROFILES[q];this.mirror?.dispose();this.mirror=undefined;this.material.setTexture('reflection',this.depthTexture);this.material.setFloat('mirrorOn',0);if(p.mirror){this.mirror=new MirrorTexture('pond-selective-reflection',p.mirror,this.scene,true);this.mirror.mirrorPlane=new Plane(0,-1,0,-.01);this.mirror.renderList=this.reflectors.filter(m=>!m.isDisposed()&&m.isEnabled()).slice(0,48);this.mirror.refreshRate=p.cadence;this.scene.customRenderTargets.push(this.mirror);this.material.setTexture('reflection',this.mirror);this.material.setFloat('mirrorOn',1);}this.effects.forEach(e=>{if(!e.event)e.mesh.setEnabled(false);});}
 refresh(){if(this.mirror){this.mirror.renderList=this.reflectors.filter(m=>!m.isDisposed()&&m.isEnabled()).slice(0,48);this.mirror.resetRefreshCounter();}}
 setContext(enabled:boolean,depth=2){this.context=enabled;this.mesh.setEnabled(!enabled);this.contextMesh.setEnabled(enabled);this.material.setFloat('contextDepth',enabled?depth:0);this.effects.forEach(e=>{e.event=undefined;e.mesh.setEnabled(false);});this.refresh();}
 compare(simple:boolean){this.mesh.material=simple?this.simple:this.material;}
 trigger(e:WaterEvent){if(!this.context&&!inPond(e.position))return;this.counts[e.type]=(this.counts[e.type]??0)+1;if(e.type==='spot_transition'){this.effects.forEach(f=>{f.event=undefined;f.mesh.setEnabled(false);});this.refresh();return;}if(e.type==='wind_change')return;const p=WATER_PROFILES[this.quality],rings=this.effects.slice(0,p.rings),empty=rings.find(f=>!f.event||this.now-f.event.time>2.4),slot=empty??rings.filter(f=>!f.event?.essential).sort((a,b)=>(a.event?.time??0)-(b.event?.time??0))[0]??rings.sort((a,b)=>(a.event?.time??0)-(b.event?.time??0))[0];slot.event=e;slot.mesh.position.set(e.position.x,.025,e.position.z);slot.mesh.rotation.y=e.direction;if(['cast_impact','feeder_impact','groundbait_impact','fish_surface_break','fish_dive','net_exit','fish_release'].includes(e.type))for(const f of this.effects.slice(28,28+Math.min(p.drops,Math.ceil(e.intensity*6))))if(!f.event||this.now-f.event.time>.65)f.event=e;this.onEvent?.(e);}
 demo(type:WaterType,position:Vector3,seed=127){this.trigger({id:this.debugId--,type,time:this.now,position:{x:position.x,y:0,z:position.z},intensity:.4,source:'visual_test',direction:0,essential:true,seed});}
 update(time:number,eye:Vector3,events:WaterEvent[],wind=0){this.now=time;this.material.setFloat('time',time);this.material.setVector3('eye',eye);this.material.setFloat('wind',wind);for(const e of events)if(e.id>this.lastId){this.lastId=e.id;this.trigger(e);}const p=WATER_PROFILES[this.quality];for(const f of this.effects){const age=f.event?time-f.event.time:99,drop=f.drop!==undefined,enabled=!!f.event&&age>=0&&age<(drop?.65:2.4)&&(!drop||f.drop!<p.drops);f.mesh.setEnabled(enabled);if(!enabled){f.event=undefined;continue;}const e=f.event!;if(drop){const n=f.drop!,angle=n*2.399+e.seed*.001;f.mesh.position.set(e.position.x+Math.cos(angle)*age*.45,e.position.y+.03+Math.sin(age/.65*Math.PI)*(.08+e.intensity*.3),e.position.z+Math.sin(angle)*age*.45);}else{f.mesh.scaling.set( .15+age*(.3+e.intensity),1,.15+age*(.3+e.intensity));(f.mesh.material as StandardMaterial).alpha=(1-age/2.4)*(.12+e.intensity*.16);}}}
 clearEffects(){this.effects.forEach(e=>{e.event=undefined;e.mesh.setEnabled(false);});}
 diagnostics(){return{quality:this.quality,activeRings:this.effects.filter(f=>f.drop===undefined&&!!f.event).length,activeDrops:this.effects.filter(f=>f.drop!==undefined&&!!f.event).length,capacity:WATER_PROFILES[this.quality],events:{...this.counts},lastId:this.lastId,mirror:this.mirror?.getSize(),surfaceLevel:0};}
}
